### ISSUE TITLE
Critical inside a module procedure

### ISSUE THREAD

**Issue by raullaasner** [sourceryinstitute/opencoarrays#10]
It says in STATUS.md that `critical` is supported. However, this is what I get:
```
[raul@x220 tests]$ cat Critical.f90 
module m
contains
  subroutine f()
    critical
    end critical
  end subroutine f
end module m
end program
[raul@x220 tests]$ mpif90 -fcoarray=lib Critical.f90 libcaf_mpi.a 
f951: internal compiler error: in gfc_enforce_clean_symbol_state, at fortran/symbol.c:3749
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
```
With `-fcoarray=single` the build is successful. Can anyone confirm if the issue is with OpenCoarrays (1.0.0), the GNU compiler (5.2.0), or something else?

**Comment by rouson** [comment]
Hi Raul,

Thanks for your interest in OpenCoarrays and for submitting this issue report.

By definition, an internal compiler error is always a compiler bug -- in part because reporting an internal compiler error in the absence of a bug is itself a bug.  However, to be certain, I tried to building the submitted module with 

mpif90 -c critical.f90 -fcoarray=lib 

so that the library is not involved because no library is specified.  The latter command also gives an ICE with a copy of the GCC trunk (6.0.0) dated 20150719.  

Please submit a bug report via the GCC Bugzilla site (https://gcc.gnu.org/bugzilla/).  Please also send the resulting Bug number to the gfortran developers at fortran@gcc.gnu.org and cc the OpenCoarrays Google Group at opencoarrays@googlegroups.com.  

Although this is a compiler issue, I'll defer to Alessandro to decide whether to keep the issue open here or not.

Damian
