### ISSUE TITLE
sign releases

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#113]
You can store public GPG keys inside the git repo itself:

http://git-scm.com/book/ch5-3.html#Tagging-Your-Releases

This then makes it convenient for others to be able to add your public key to their keychain and verify any tags or commits you have signed. Just signing tags is sufficient to sign the entire git history on the branch that is tagged, since each commit's SHA is a product of hashing that commits content with its parent commit's SHA.

**Comment by zbeekman** [comment]
We'll start doing this, at least manually, with the next release.

I've tagged and added (as a raw git object) my PGP public key.

This is how you can fetch it and add it to your GPG keychain:

```bash
$ git fetch --tags origin # assuming origin is sourceryinstitute/opencoarrays
$ git show zbeekmanpubkey | gig --import
```

Then tags can be verified with: `git tag -v 1.3.0`

The release archives can also be signed and verified with gpg.

Get it for OS X from [GPGTools}(https://gpgtools.org) or on other/all platforms from [GnuPG](https://www.gnupg.org)

**Comment by zbeekman** [comment]
[Release 1.3.0](https://github.com/sourceryinstitute/opencoarrays/releases/tag/1.3.0) is the first signed release. It should be easy/straightforward to automate some/all of this with Travis-CI for future releases.

**Comment by rouson** [comment]
It would be a good idea to edit the release page near the bottom to explain the different files.  I’m not clear on what each one is are so it’s certainly the case that others won’t be certain either. While we’re at it, it wouldn’t hurt to request that people download one of the first three files, which we posted, rather than the final two files, which GitHub posts automatically.

________________________________
Damian Rouson, Ph.D., P.E.
President, Sourcery Institute
http://www.sourceryinstitute.org
+1-510-600-2992 (mobile)

**Comment by zbeekman** [comment]
OK, take a look at it now. [You can edit it](https://github.com/sourceryinstitute/opencoarrays/releases/edit/1.3.0) too if you like.

**Comment by rouson** [comment]
Nice!!!!  That documentation is a work of art.  :)
