### ISSUE TITLE
MPI library requirements

### ISSUE THREAD

**Issue by LadaF** [sourceryinstitute/opencoarrays#146]
The documentation does not specify which MPI library versions are acceptable. My OpenMPI 1.6.5. definitely isn't.

Is there any way to tell the install script to install it's own MPICH? I have quite some libraries built against OpenMPI and I do not want to rebuild them all.

```
*** All prerequisites will be downloaded to, built in, and installed in ***
/home/lada/OpenCoarrays-1.3.2/install_prerequisites
*** OpenCoarrays will be installed in the above location also.        ***
Ready to proceed? (y/n) y
install.sh: Checking whether mpich executable mpif90 is in the PATH...yes.
install.sh: Checking whether mpif90 is in the directory in which install.sh
            installs it by default and whether the user has executable permission for it...no.
install.sh: Checking whether mpif90 in PATH wraps gfortran... yes.
install.sh: Checking whether mpif90 in PATH wraps gfortran version 5.3.0 or later... yes.
install.sh: Using the mpif90 found in the PATH.
install.sh: Updated dependency stack (top to bottom = left to right):
( none )
install.sh: Remaining mpich dependency stack (top to bottom = left to right):
( none )
install.sh: Checking whether cmake is in the PATH...yes.
install.sh: Checking whether cmake is in the directory in which install.sh
            installs it by default and whether the user has executable permission for it...yes.
install.sh: Using the cmake installed by install.sh
install.sh: Updated dependency stack (top to bottom = left to right):
( none )
install.sh: Remaining cmake dependency stack (top to bottom = left to right):
( none )
-- Disabling optimization flags due to GCC < 5.4 bug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lada/OpenCoarrays-1.3.2/opencoarrays-build
[  4%] Built target caf_single
Scanning dependencies of target caf_mpi
[  5%] Building Fortran object src/mpi/CMakeFiles/caf_mpi.dir/__/extensions/opencoarrays.F90.o
[  6%] Building C object src/mpi/CMakeFiles/caf_mpi.dir/mpi_caf.c.o
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘locking_atomic_op’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:213:7: warning: implicit declaration of function ‘MPI_Compare_and_swap’ [-Wimplicit-function-declaration]
       MPI_Compare_and_swap (&newval,&compare,value, MPI_INT,image_index-1,
       ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:218:7: warning: implicit declaration of function ‘MPI_Win_flush’ [-Wimplicit-function-declaration]
       MPI_Win_flush (image_index-1, win);
       ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘mutex_lock’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:266:2: warning: #warning Locking for MPI-2 is not implemented [-Wcpp]
 #warning Locking for MPI-2 is not implemented
  ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘mutex_unlock’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:308:2: warning: #warning Locking for MPI-2 is not implemented [-Wcpp]
 #warning Locking for MPI-2 is not implemented
  ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_init’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:391:7: error: too many arguments to function ‘MPI_Alloc_mem’
       MPI_Alloc_mem(sizeof(int), MPI_INFO_NULL, &img_status, stat_tok);
       ^
In file included from /home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:42:0:
/usr/local/include/mpi.h:1039:20: note: declared here
 OMPI_DECLSPEC  int MPI_Alloc_mem(MPI_Aint size, MPI_Info info,
                    ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_finalize’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:410:3: warning: implicit declaration of function ‘MPI_Win_sync’ [-Wimplicit-function-declaration]
   MPI_Win_sync(*stat_tok);
   ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:429:7: warning: implicit declaration of function ‘MPI_Win_unlock_all’ [-Wimplicit-function-declaration]
       MPI_Win_unlock_all(*p);
       ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_atomic_cas’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:2259:2: warning: #warning atomic_cas for MPI-2 is not yet implemented [-Wcpp]
 #warning atomic_cas for MPI-2 is not yet implemented
  ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_atomic_op’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:2323:3: warning: #warning atomic_op for MPI is not yet implemented [-Wcpp]
  #warning atomic_op for MPI is not yet implemented
   ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_event_post’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:2364:4: warning: #warning Events for MPI-2 are not implemented [-Wcpp]
   #warning Events for MPI-2 are not implemented
    ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_event_wait’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:2421:10: warning: implicit declaration of function ‘MPI_Fetch_and_op’ [-Wimplicit-function-declaration]
   ierr = MPI_Fetch_and_op(&newval, &old, MPI_INT, image, index*sizeof(int), MPI_SUM, *p);
          ^
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c: In function ‘_gfortran_caf_event_query’:
/home/lada/OpenCoarrays-1.3.2/src/mpi/mpi_caf.c:2465:2: warning: #warning Events for MPI-2 are not implemented [-Wcpp]
 #warning Events for MPI-2 are not implemented
  ^
make[2]: *** [src/mpi/CMakeFiles/caf_mpi.dir/mpi_caf.c.o] Error 1
make[1]: *** [src/mpi/CMakeFiles/caf_mpi.dir/all] Error 2
make: *** [all] Error 2
Something went wrong. Either the user lacks executable permissions for the
OpenCoarrays compiler wrapper (caf), program launcher (cafrun), or prerequisite
package installer (build), or these programs are not in the following, expected
location:
/home/lada/OpenCoarrays-1.3.2/opencoarrays-installation/bin.
Please review the following file for more information:
/home/lada/OpenCoarrays-1.3.2/opencoarrays-installation/install-opencoarrays.log
and submit an bug report at https://github.com/sourceryinstitute/opencoarrays/issues
[exit 100]

```

**Comment by zbeekman** [comment]
@LadaF The install script will install MPICH if it detects you are missing an MPI implementation. We would like to improve the argument parsing of the install script (see #50 ) to allow us to add more options and better control, but in the mean time you should be able to "trick"  `install.sh` into installing MPICH for you.

Looking at the top of `find_or_install(){...` in `install.sh` [here](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh#L130-L170) you should be able to trick `install.sh` into installing MPICH for you by removing `mpif90` from your PATH. Can you try that and let me know how it goes?

**Comment by milancurcic** [comment]
FWIW, gcc-5.2.0 and openmpi-1.10.0 work well for me. But I installed opencoarrays by hand (cmake;make;make install), not with `install.sh`. Not sure if it makes a difference.

**Comment by zbeekman** [comment]
@milancurcic CMake manual install is my preferred method too.... but the `install.sh` is a catch all that knows how to build a lot of dependencies that can be hard to install by hand, if your package manager has old versions....

@LadaF I can now confirm that for optimal OpenCoarrays support, you need an MPI-3 implementation.

**Comment by rouson** [comment]
@all

The short answer: Building with CMake is fine, but please continue to submit Issues that we can use to improve install.sh.   

The long answer (only read if you're interested):

As you know, install.sh wraps CMake, which wraps Make.  It's possible to build with either of the three (e.g., there is still a static [Makefile](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/Makefile)), but each of the aforementioned wrappers includes logic that is missing in the wrapped build system.  For example, [install.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh) creates a "setup.sh" file that the user can source to define useful environment variables based on the system set-up detected during the installation. Also, install.sh wraps a  [build](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build) script that it queries for the minimum version requirements.  If you do install via CMake, which requires that you first have all the prerequisite packages, you should at least execute the following commands to determine the minimum required version of each prerequisite (which is also the default version that install.sh installs):
    
    cd install_prerequisites
    ./build gcc --default --query-version
    ./build mpich --default --query-version
    ./build cmake --default --query-version

Also, if you're building prerequisites from source (rather than via package management software), there is some platform-specific logic in the install.sh that you might otherwise have to discover the hard way. For example, CMake will fail to build on OS X with any gcc other than the gcc that Apple ships with XCode so install.sh checks the operating system and invokes the correct gcc when it builds CMake.

I can't think of anything other than the above reasons for choosing install.sh over building directly with CMAke currently, but just be aware that the list of reasons to prefer install.sh might grow over time.

**Comment by rouson** [comment]
> On Feb 9, 2016, at 12:24 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> @LadaF <https://github.com/LadaF> The install script will install MPICH if it detects you are missing an MPI implementation.
> 
Currently, the install script checks the result of “mpif90 --version,” which actually returns the version of the Fortran compiler that mpif90 wraps.  At some point we should insert logic to check the version of the mpi implementation too, but the current approach means the script will accept any MPI implementation that wraps a sufficiently recent version of gfortran (>=5.3). 

@afanfa is working on backporting Fortran 2015 events to the gcc-5 branch so GCC 5.4 will support events when it releases. Given the importance of events to parallel performance and scalability, we will consider bumping the minimum gfortran version number when 5.4 releases.  But we don’t necessarily need to consider to bumping to 6 when that releases because the most significant new feature in 6 (submodules) does not relate to CAF.

> We would like to improve the argument parsing of the install script (see #50 <https://github.com/sourceryinstitute/opencoarrays/issues/50> ) to allow us to add more options and better control, but in the mean time you should be able to "trick" install.sh into installing MPICH for you.
> 
> Looking at the top of find_or_install(){... in install.sh here <https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh#L130-L170> you should be able to trick install.sh into installing MPICH for you by removing mpif90 from your PATH. Can you try that and let me know how it goes?

Yes, temporarily removing mpif90 from your PATH will trick install.sh into installing MPICH for you, but OpenMPI should work.  We simply recommend MPICH or MVAPICH because we have found them to be slightly more robust.

Damian

**Comment by zbeekman** [comment]
@LadaF did you have any luck building OpenCoarrays? (Either by "tricking" `install.sh` to download and build a new MPICH install for you, or installing a new MPI implementation and using the CMake or install.sh build techniques...)

**Comment by rouson** [comment]
Our current refactoring effort for install.sh will result in more and better options for passing arguments to install.sh, including for example, 

./install.sh --with-mpi=/opt/openmpi/

which will tell install.sh to use the MPI implementation in the specified path.  Because the improved argument parsing is Issue #50, I'm closing the current issue and suggesting @LadaF watch for a resolution to issue #50 or watch for our upcoming release [1.4.0](https://github.com/sourceryinstitute/opencoarrays/milestones/1.4.0%20release), for which I just set a target date of April 30, but target dates are just wish lists right now, given that most related work is volunteer effort.
