### ISSUE TITLE
Update gfortran minimum to 5.4 when it releases

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#148]
@afanfa just committed support for Fortran 2015 events on the gcc-5 branch.  Given the important and positive performance implications of events, let's plan to set the next release from the gcc-5 branch (release 5.4) as the minimum version when the [GCC](http://gcc.gnu.org) 5.4 release happens.

**Comment by zbeekman** [comment]
OK, just FYI, right now the build.sh script fails (silently) on the Travis-CI Ubuntu virtual machines because only 5.2 is available from the toolchain-r/test PPA. If we upgrade to 5.4 as a dependency, then it will also fail on the OS X Travis-CI images, until a GCC-5.4 Homebrew Formula is submitted, and accepted. I can probably do this relatively quickly, unless someone else beats me to it, but it might still happen a few days if not a week or two after the 5.4 release.

Also, additional question: Does OpenCoarrays currently support events but is blocked by gfortran?

**Comment by rouson** [comment]
Yes, OpenCoarrays supports events but is blocked by gfortran 5.3.  Event support is now in the gfortran trunk (6.0.0) and in the gcc-5 branch (which will be released as 5.4).

**Comment by zbeekman** [comment]
Great! It would be nice to include/enable unit tests for events when 5.4 is released. I'll try to look into this.

**Comment by rouson** [comment]
Awesome!  I recommend checking [TS 18508](http://isotc.iso.org/livelink/livelink?func=ll&objId=17288706&objAction=Open): In Annex A, "A.3 Clause 7 notes" contains several events examples.  Possibly those could be converted into tests.

**Comment by rasmussn** [comment]
Events?  Way cool!

I need events for the CAFe stuff.

-craig

**Comment by rouson** [comment]
@rasmussn Yes, way cool.  And you can access events now if you build OpenCoarrays with the gfortran trunk (6.0.0) or if you checkout the gcc-5 branch via svn.

**Comment by rasmussn** [comment]
I'll add the new 2015 grammar to OFP then.

-craig

**Comment by rouson** [comment]
@zbeekman now that we have updated to 6.1.0 as the default and added flags by which users can override the default, I'll close this issue.
