### ISSUE TITLE
Missing installation arguments not detected

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#189]
@zbeekman,

Apparently [parse_command_line.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/use-case/parse_command_line.sh) fails to detect missing arguments in several situations.  One situation that appears to be handled correctly is when the corresponding option is the only one on the command line :  

```
./install.sh -j
```

Another that is handled properly is when the option is the last one on the command line and is preceded by an option that has its required argument:

```
./install.sh -p gcc -j 
```

The above two commands generate error messages that indicate that -j requires an argument. However, adding another option that requires an argument suppresses the desired error message:

```
./install.sh -p gcc -j -f
```

 The latter command proceeds without an error message.  Likewise, no error message results when the option precedes a correctly formatted option:

```
./install.sh -j -p gcc
```

which does not generate an error message.

**Comment by zbeekman** [comment]
I am aware of this limitation and think I know how to resolve it.

**Comment by zbeekman** [comment]
@rouson, I have thought about this some more. I think in general, this is essentially the correct behavior, since the script is receiving an argument to the flag in question in all of the cases, the only issue is that the user is passing an additional flag as the argument, rather than the actual value. As such, I'm tempted to mark this as "won't fix" and file it under user error. What do you think? Extensive validation of user inputs might get a bit hairy, and I'm not sure it should be a top priority. Thoughts?

**Comment by rouson** [comment]
Thanks for giving this more thought.  Feel free to close the issue.

**Comment by zbeekman** [comment]
Ok, I'll close this for now. If we see any truly anomalous behavior, we can address it in the future.
