### ISSUE TITLE
ftp-url.sh: line 27: ftp: command not found

### ISSUE THREAD

**Issue by jeffhammond** [sourceryinstitute/opencoarrays#192]
I can't build OpenCoarrays in Travis CI because `ftp` is not installed:
```
ftp-url.sh: line 27: ftp: command not found
```
I saw issues indicating that `ftp` has been replaced by `wget` or `curl`, which I know work in Travis CI.

Am I doing something wrong, because I can't figure out why `ftp` is used here, or why it is failing.

Details: https://travis-ci.org/jeffhammond/PRK/jobs/133842969

**Comment by jeffhammond** [comment]
By the way, I just switched to installing all the dependencies myself and using CMake directly, so `install.sh` isn't critical for me.

So basically, if this isn't a trivial fix, just close and ignore.

**Comment by rouson** [comment]
This won't be hard to fix.  I just need some advice to help me choose the best download mechanism. 

With the latest release or a git clone of the master branch, install.sh exclusively uses curl on OS X (which is probably what you saw) because the XCode command-line tools provide curl.  On Linux,  the script uses ftp whenever possible based on my naive assumption that ftp would be the most common.  On Linux, the script uses wget for sites that don't offer ftp access.  

I could change the script so that it checks for ftp, then wget, then curl, and uses whichever is the first found that works for the given package (some download sites don't allow ftp access).  How does that sound?

We've talked about using package management software, but one problem is the plethora of options: macports, homebrew, apt-get, yum, linuxbrew, pacman, etc.  Another problem is that some of the package managers default to installing in locations that require sudo privileges.

**Comment by jeffhammond** [comment]
ftp->wget->curl sounds fine to me.  I've never used a machine that didn't have wget, FWIW.

You are right about sudo and packmans, but some folks might be trusting enough to run `sudo ./install.sh`.

The case I care most about is Homebrew, which doesn't require sudo in the standard usage.  My machines running `apt` and `yum` require `sudo`, obviously.

**Comment by rouson** [comment]
I think I'm going to reverse the order: curl->wget->ftp.  Now that we're going to allow for using any of the  three on any platform, robustness seems more important than ubiquity.  My guess is that curl is the most robust when present.  For example, it can handle things like URL redirections gracefully. I'm working on the edits now and will create a pull request that addresses this issue if my local testing goes ok.

**Comment by rouson** [comment]
Pull request #196 addresses this.  Closing.

**Comment by zbeekman** [comment]
@jeffhammond Our build script now does some more clever system introspection to determine what download capabilities are available and choose an appropriate one. These changes are in the latest release and on master. Please let me know if you find this problem persists for any reason. Thanks!
