### ISSUE TITLE
Cleanup license file for automatic license detection

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#233]
@rouson would you be willing to modify the LICENSE file a little bit to allow automatic license detection by github? For example check out TAU Commander's license file: https://github.com/ParaToolsInc/taucmdr/blob/master/LICENSE and the automatic license detection by github:

![screen shot 2016-10-19 at 8 28 33 am](https://cloud.githubusercontent.com/assets/279612/19525537/1cc6be1e-95d6-11e6-984b-51ca86cf8ae3.png)

**Comment by rouson** [comment]
:clap:  If I my quick check is correct, the wording is identical and the only differences are in line endings and the names of the copyright holders.  If that's the case, then this should be no problem. Otherwise, if there are any substantive differences, I assume we might need to seek the approval of everyone who contributed under the previous license, but that's a pretty short list.

**Comment by zbeekman** [comment]
Line endings may be an issue, but I think the problem is the longer header
for opencoarrays. I'll do some testing.
