### ISSUE TITLE
RFE: Support building shared libraries

### ISSUE THREAD

**Issue by opoplawski** [sourceryinstitute/opencoarrays#245]
Attempting to build shared libraries results in:
```
CMake Error at src/mpi/CMakeLists.txt:27 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "caf_mpi".
```
Is there a specific reason that this isn't supported?

**Comment by zbeekman** [comment]
Not that I'm aware of... overhauling the CMake build system a bit has been on my todo list for a while. 

Can you share what you did to produce that error? I.e., how do you normally build shared libs with CMake?

**Comment by opoplawski** [comment]
To enable shared libraries you pass -DBUILD_SHARED_LIBS:BOOL=ON

All library targets also need a LIBRARY DESTINATION then in addition to the ARCHIVE DESTINATION.  Also, you'll want to set the SOVERSION for the libraries - probably starting with 0.

**Comment by zbeekman** [comment]
Ok thanks for the deets. I'll try to get to this soon.

**Comment by zbeekman** [comment]
> Also, you'll want to set the SOVERSION for the libraries - probably starting with 0.

Why starting with 0 vs the current MAJOR.MINOR?

**Comment by zbeekman** [comment]
@opoplawski I thought you had responded to my latest comment, but I can't find any evidence of it here or in my email account. If I am mis-remembering, then please ignore this message, but if you did respond, could you please re-send the message?

I have been doing some more reading about shared libraries, most recently [on stack overflow](http://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work) and [in this IBM article](http://www.ibm.com/developerworks/linux/library/l-shlibs/index.html).

The more I read and contemplate this issue, the more I realize that there are some subtleties that may not be appropriately addressed by our current installation logic:

1. Since we are using semantic versioning I still contend that an SO versioning scheme of lib.so.MAJOR.MINOR is appropriate. CMake creates the appropriate symbolic links. I still contend that there is no reason to start explicitly at 0, but am willing to change my mind if there is a good reason to follow this convention.
2. The ABI compatibility is not entirely dictated by the semantic versioning of the library: there are cases in which it could change based on the build: First of all there may be some advanced features controlled by `#ifdef`s that aren't publicized in CMake, however, I think it's fair to assume that users play with these at their own peril.
3. gfortran ABI: OpenCoarrays interfaces directly with gfortran and the gfortran runtime. To support different gfortrans, OpenCoarrays uses conditional compilation via introspection and `#ifdef`s guarding code for a specific version of gfortran, where needed. Therefore OpenCoarrays compiled with one version of gfortran is not necessarily ABI compatible with one compiled with a different version. I'm unsure of how to best handle this scenario to support cases where multiple versions of GCC/gfortran may be installed on a given system. One easy, but brutish hack, would be for the `caf` and `cafrun` scripts to modify `LD_LIBRARY_PATH` and to use full paths to GCC and MPI, based on what OpenCoarrays was compiled with. With some careful thought, multiple OpenCoarrays can be installed on a given system using different toolchains, so long as the installed files are handled carefully. I set up something like this for JSON-Fortran. (See also #79)
4. Fortran module file ABI: Submodules could fix this, by allowing the module defining the interfaces to be distributed in source form and then distributing the compiled submodules, so that the `.mod` files are always recompiled along with client  code (via cmake). This is only really applicable to the experimental source transformations for GCC < 5.2 or 5.3 and other compilers, and has to do with the ABI but not shared objects explicitly.

**Comment by zbeekman** [comment]
@bradking: I was just wondering if you had any expert advice for us at OpenCoarrays concerning the above discussion.

**Comment by bradking** [comment]
@zbeekman for libraries that are careful with their ABI then having the `SOVERSION` set to a value independent of the project version is common.  The latter can go in the `VERSION` property which is only for human reference.  If the soversion happens to be the project major version then great, but they don't have to be tied in principle.

Sometimes when a library's ABI or content varies with external dependencies then the library's name itself includes information about that.  The name might include something about what ABI or mangling is used.  A dependent project may then choose at link time (or earlier) which variant to use because the library name to be linked is different.
