### ISSUE TITLE
install.sh calls gcc with the wrong path

### ISSUE THREAD

**Issue by LaHaine** [sourceryinstitute/opencoarrays#306]
I've tested install.sh again and let it install all prequisites. In the end, it tries to compile opencoarrays, but it is using the wrong path for the just compiled gcc, /batch/test/opencoarrays/prerequisites/installations/gcc instead of /batch/test/opencoarrays/prerequisites/installations/gcc/6.1.0/bin/gcc .

**Comment by LaHaine** [comment]
[install-opencoarrays.log.txt](https://github.com/sourceryinstitute/opencoarrays/files/703820/install-opencoarrays.log.txt)

**Comment by zbeekman** [comment]
Ah, I see.... this is because of the greedy `%%` parameter expansion and the fact that gcc appears twice once in the path and once as the name of the binary. We need to handle/parse the output of `mpicc -show` much more carefully. I also don't think we can cavalierly just discard the binary name either since some systems are gcc-6 etc.
