### ISSUE TITLE
Don't delete files generated at config time when `make clean`

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#31]
I think this is caused only by the examples from scientific software design, like the burgers example.

**Problem description:** `make clean` followed by `make` fails because `compiler_capabilities.txt` is added to `additional_make_clean` property in CMake which tells make to remove the file, but it is generated to configure time, not compile time, and therefore should probably not be removed by `make clean`

**Comment by rouson** [comment]
Two respsonses:
1. Over time, this issue will disappear because I no longer use compiler_capabilities.txt files in new code and I'll eventually remove them from old code when I get around to doing some housecleaning. A better approach is to use add_definitions(...).  
2. The compiler_capabilities.txt files get generated at configure time (as you note), used at compile time, and then are not needed after a successful build. My previous work flow involved something like

mkdir Build
cd Build
../buildscripts/gnu-compilers-cmake.sh
make
make install
make clean

Thus, I usually only do "make clean" after all building is done.  Of course, iterations such as

make
make clean
make

won't work because a new configuration step is needed after the "make clean". Probably the best approach is to keep this Issue open as a reminder to me to refactor old codes to replace compiler_capabilities.txt with add_definition(...).  It will take a bit of grunt-work and is not a super-high priority, but I imagine I'll get to it within the next 1-2 months.

**Comment by zbeekman** [comment]
Also, should probably generate files in the binary directory, not the source directory... I'll try to fix this.
