### ISSUE TITLE
co_reduce: Segfault with -Wl,-z,noexecstack

### ISSUE THREAD

**Issue by vehre** [sourceryinstitute/OpenCoarrays#317]
Forking this issue from #172, because this is something different. Let's track the noexecstack issue here.

**Comment by zbeekman** [comment]
Do you think this might be due to the global procedure pointer? I'm wondering if fixing #324 might fix this, but that's somewhat wild speculation on my part

**Comment by vehre** [comment]
[Comment 1](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71729#c1) gives a good explanation why and when this is happening.
Unfortunately can't we do anything about it, beside compiling with executable stack. This means, that we need to override the -Wl,-z,noexecstack given at the compiler command line at least when compiling Debug or RelWithDebInfo for at least MPICH (haven't tested for OpenMPI yet). This can be done by adding -Wl,-z,execstack to the compiler command line. I could figure how to do this in the CMakeLists.txt and the caf-driver, but I assume, that one of your @zbeekman or @rouson is faster doing so. Therefore am I asking you to do it.

**Comment by zbeekman** [comment]
@vehre: Great, I'd be happy to work on this. Do you think we should just always add `-Wl,-z,execstack`, or should I try to parse the linker flags and remove  `-z,noexecstack` if it is present? (This latter approach is possible because [`FindMPI`](https://cmake.org/cmake/help/latest/module/FindMPI.html) extracts the compiler and linker flags from the mpi wrapper scripts so we could, in theory, search them and remove the `-z,noexecstack` linker flag if it is present.)

**Comment by vehre** [comment]
@zbeekman I leave the decision of what is easier to you. As to know the compiler accepts having noexecstack and execstack on the command line.
The only issue we have, when both are on the command line is, that execstack must come after noexecstack. When you can assure the latter, then feel free to just add it.
