### ISSUE TITLE
events - confirming or not

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/opencoarrays#330]
`newblue4> cat z.f90`

```fortran 
use, intrinsic :: iso_fortran_env, only : event_type
type( event_type ) :: evar[*]
logical, allocatable :: l(:)[:]
integer :: nimgs

nimgs = num_images()

! implicit sync
allocate( l( nimgs )[*], source = .false. )

l( this_image() ) [ nimgs ] = .true.
event post( evar[ nimgs ] )

if ( this_image() .eq. nimgs ) then
  event wait( evar, until_count = nimgs )
  write (*,*) l
end if
end
```

```
newblue4> caf -Wall z.f90 
newblue4> cafrun -np 16 ./a.out 
 T F F F F F F F F F F F F T T T
newblue4> cafrun -np 16 ./a.out
 T F F F F F F F F F F F F F F T
newblue4> cafrun -np 16 ./a.out
 T T T T T T F T T T T T F T F T
newblue4> 
```

I expected the output to be all values true.
So probably the code is not conforming,
but I can't see why.

Any hint?

Thanks

Anton

**Comment by zbeekman** [comment]
Hi Anton (@mexas), thanks for the bug report!

This is due to #243 ([GFortran PR 78505](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78505)) which required changes on the compiler side, but has been fixed on GCC trunk and in the forthcoming GFortran 7.1.0 release. What is happening is that the synchronization his happening after the allocation, but *before* the assignment from the `source=` clause. As a work around, if you insert a `sync all` after the sourced allocation this code performs as expected.

Let us know if you have any further questions or difficulties, but I'm going to close this as a duplicate for now. If there is any issue that I have failed to address we can reopen.
