### ISSUE TITLE
build failure on arm7

### ISSUE THREAD

**Issue by finneyb** [sourceryinstitute/opencoarrays#38]
just a FYI and not a complaint.  The command ./build gcc failed part way through the portion of the build working on stage1 building gcc itself.  The preliminary building of the some of the libraries went smoothly.

**Comment by rouson** [comment]
Thanks for your report!  All feedback is welcome.  I don't recall if you're the person who was simply trying to build GCC or whether you actually want to build OpenCoarrays.  The OpenCoarrays installation script (install.sh) only tries to build gcc/g++/gfortran if it's missing or it detects that the gfortran in the path is older than version 5.1.0 or if it doesn't find a previous gfortran build installed by itself (install.sh). If you can manage to build gfortran 5.1.0 or later by other means and you add it to your PATH, then the OpenCoarrays installation will find it, not try to build a new one, and move on to building MPICH and CMake if necessary.

Because this is a problem in the GCC build, would you mind emailing the gfortran developers at fortran@gcc.gnu.org and cc'ing me at damian@sourceryinstitute.org?  That way you'll be in the loop on all replies. For now, I'll close this as it's more of a GCC issue.  I haven't heard much about building gfortran on ARM architectures, but I wonder if the following discussion thread is helpful at all:

https://gcc.gnu.org/ml/fortran/2012-01/msg00177.html

Damian

**Comment by finneyb** [comment]
On 12/3/2015 9:59 PM, Damian Rouson wrote:
> Thanks for your report! All feedback is welcome. I don't recall if
> you're the person who was simply trying to build GCC or whether you
> actually want to build OpenCoarrays. The OpenCoarrays installation
> script (install.sh) only tries to build gcc/g++/gfortran if it's missing
> or it detects that the gfortran in the path is older than version 5.1.0
> or if it doesn't find a previous gfortran build installed by itself
> (install.sh). If you can manage to build gfortran 5.1.0 or later by
> other means and you add it to your PATH, then the OpenCoarrays
> installation will find it, not try to build a new one, and move on to
> building MPICH and CMake if necessary.
>
> Because this is a problem in the GCC build, would you mind emailing the
> gfortran developers at fortran@gcc.gnu.org <mailto:fortran@gcc.gnu.org>
> and cc'ing me at damian@sourceryinstitute.org
> <mailto:damian@sourceryinstitute.org>? That way you'll be in the loop on
> all replies. For now, I'll close this as it's more of a GCC issue. I
> haven't heard much about building gfortran on ARM architectures, but I
> wonder if the following discussion thread is helpful at all:
>
> https://gcc.gnu.org/ml/fortran/2012-01/msg00177.html
>
> Damian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/38#issuecomment-161884950>.
>

Thanks

I suspect that the problem is that the build script did not find 
gfortran since it is accessible via the command gfortran-5.  I will make 
an link to gfortran and try again.

Brad

**Comment by rouson** [comment]
You're welcome.  Please let me know how it goes.

Damian

**Comment by zbeekman** [comment]
FWIW, it might be worth checking in the `install.sh` and `build` for availability of `gcc-5` and `gfortran-5`... although this does increase the complexity. I would imagine a number of linux distros keep gcc and gfortran pegged at version 4.x for stability, even if version 5 is on the system
