### ISSUE TITLE
allocatable coarrays take too long to allocate on a large number of images

### ISSUE THREAD

**Issue by gutmann** [sourceryinstitute/OpenCoarrays#420]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: 1.8.2
- Fortran Compiler: gfortran/6.3.0
- C compiler used for building lib: unknown pre-installed likely gcc/6.3.0
- Installation method: pre-installed on supercomputer
- Output of `uname -a`: Linux cheyenne3 3.12.62-60.64.8-default #1 SMP Tue Oct 18 12:21:38 UTC 2016 (42e0a66) x86_64 x86_64 x86_64 GNU/Linux
- MPI library being used: MPT/2.15 (vendor:SGI)
- Machine architecture and number of physical cores: [Cheyenne: Xeon + infiniband, >9k cores tested](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne)
- Version of CMake: unknown pre-installed likely cmake/3.7.2

## Observed Behavior ##
Allocating a few coarrays (e.g. `allocate(coarray(nx,ny,nz)[*])`) can take 1/2 hour on a large number of cores.  See tests case and documentation here: https://github.com/gutmann/caf_alloc_test

## Expected Behavior ##
Allocating coarrays should take longer on more cores, but not such that the entire permittable wall clock in a job scheduler expires before allocation completes...

## Steps to Reproduce ##
```
git clone https://github.com/gutmann/caf_alloc_test
cd caf_alloc_test
make
# if necessary, submit job to your job scheduler here
cafrun -np 360 ./alloc_test
```

**Comment by rouson** [comment]
@afanfa Because this issue first showed up on Cheyenne, I'm hoping you won't mind investigating it so I'm assigning this to you.  If you won't have the time, feel free to let me know and we'll try to reproduce a similar result elsewhere.

**Comment by vehre** [comment]
Please note: With fixing #399 register() will look significantly different and use far less synchronization and MPI_Allocs.

**Comment by rouson** [comment]
@vehre Do you have anytime to work on this?  I think @gutmann would agree that it severely limits the utility of OpenCorrays at scale.  He discovered this in the process of performing scaling studies to gather data for a paper that is due July 31.

**Comment by vehre** [comment]
Well, in the register()-routine it is already fixed. But I haven't had time to port the new style to get_by_ref(), which is used in the testcases far more often than before. Because I am in trouble with my current project, I will not have to finish this before July 31.

**Comment by rouson** [comment]
@vehre Thanks for the quick replies and good luck with your current project.  @sfilippone You might have the MPI expertise to look at these.  I believe @afanfa is out of the office.

**Comment by sfilippone** [comment]
Will take a look asap

**Comment by vehre** [comment]
Well, looking again at this. The fix for #399 will not fix this issue, because #399 addresses a gcc7 issue only, but here we are using gcc6.3, i.e. the very old style.

**Comment by gutmann** [comment]
Well, I could probably switch to gcc7 but, IIRC, there is an issue with gcc7 not actually working with opencoarrays and sending data over MPI in the first place... (or something like that, @rouson, do you remember what the issue is?)  Something about the interface for one of the two (gcc or OCA) getting revamped and just having stubs for some routines?  

I'm also not sure what it will take for me to install an updated OCA on Cheyenne that will work with the MPT mpi library (though I think openMPI and others are available too). I could see it being quasi trivial, or I could see it being a nightmare of reconfiguring make/cmake/etc scripts to connect to the right libraries. (For some of us that is a nightmare ;) )

For now I just won't test scaling beyond ~3600 cores on gcc, though hopefully we will soon on intel and cray... it just won't look good for OCA when those plots stop at ~3600 :P

**Comment by vehre** [comment]
Sending data over MPI works as long as it does not affect allocatable components or allocatable objects at the target. But switching to gcc7 will not solve your issue, because the allocate for gcc7 is even more complicated and allocating more objects than the gcc6 one.

**Comment by gutmann** [comment]
Ah that was it, thanks... yes that would be a problem still, thanks!

**Comment by vehre** [comment]
Sorry for the inconveniences. I am on another project and the moment and my time is limited.

**Comment by zbeekman** [comment]
@gutmann, if you need help installing OpenCoarrays against MPT or OpenMPI let me know. As discussed, it sounds like GCC 7 is not the right approach, was this the only reason you wanted to do a new install on Cheyenne?

**Comment by gutmann** [comment]
@zbeekman, thanks!  I'm more thinking that in a few months if/when this is fixed, I (or @afanfa ) will need to install an updated version on Cheyenne.  This can probably be in my home directory, though @afanfa may be able to get it installed for all users which would be preferable. 

gcc7 is already available on Cheyenne, and they are pretty good about installing updates to various packages, though I don't know how many are using OCA on Cheyenne, so it may not be a high priority for our computing group.

**Comment by rouson** [comment]
@vehre, I just built OpenCoarrays 1.9.0-32-g7dbcf92 using GCC 7.1 and the non-developer tests of allocatable components pass:
```
      Start  7: register_alloc_comp_1
 7/43 Test  #7: register_alloc_comp_1 ............   Passed    0.09 sec
      Start  8: register_alloc_comp_2
 8/43 Test  #8: register_alloc_comp_2 ............   Passed    0.09 sec
      Start  9: register_alloc_comp_3
 9/43 Test  #9: register_alloc_comp_3 ............   Passed    0.09 sec
      Start 10: async_comp_alloc
10/43 Test #10: async_comp_alloc .................   Passed    0.14 sec
```
Probably I'm missing something, but maybe you could give more detail on what was meant by, "Sending data over MPI works as long as it does not affect allocatable components or allocatable objects at the target."

**Comment by gutmann** [comment]
FYI for anyone else reading this, it sounds like the issue is that gcc7+opencoarrays can not to puts (e.g. `array(:)[other_image]=array(:)` ) but maybe it can do gets (`array(:) = array(:)[other_image]`) over MPI with allocatable data.

**Comment by zbeekman** [comment]
@gutmann we need to wait to hear from @vehre, but I don't think this is true in general, but it may be true in the specific case of allocatable components. I'm investigating.

**Comment by gutmann** [comment]
Agreed, that is what I meant by with allocatable data, but I guess you mean it is even more specific to allocatable components of derived types? While that is sort of a special case, it may also be one of the most common cases outside of simple tests programs (I think pretty much every piece of vaguely modern Fortran code I have written or used has used allocatable arrays that are components of a derived type as the core data structure)

**Comment by zbeekman** [comment]
I'm starting to get confused as to what is allowed in F2008 vs the
allocatable components introduced in the TS. I agree with you that it's a
feature we want to add, and as quickly as we can, but right now it is
highly experimental and the complexities of accomplishing this are numerous
including changes needed on the GFortran compiler side.

Hopefully I can find some time (not today most likely, abstracts due and
other fires) to refresh my memory on the semantics for what is allowed in
pure F2008 vs the additions from the TS "Additional Parallel Features..."
and also run some tests to better illustrate what does and does not
currently work.

**Comment by rouson** [comment]
For now, the top priority is that we document capabilities clearly and make any associated error messages more descriptive.  That's the point of issue #422, which should be quick to fix when one of us gets around to it (I hope to take a whack at it later this week).  I'm a big fan of incremental feature addition so it was a really big step when we started providing experimental support for allocatable components inside derived-type coarrays, but I think we all agree that introducing a regression in allocatable components of non-coarrays is very unfortunate regression that is likely to be a deal-breaker for a lot of users. @vehre, @zbeekman, and @sfilippone , we might need to put our heads together soon and start going through the relevant code to see if we can come up to speed on the underlying issues and collectively devise a solution at least on the library side.  If the solution requires modifying the compiler, that will probably have to wait for  @vehre or @afanfa who are best qualified to address this but have other work commitments that prevent them from working on it anytime soon.

**Comment by rouson** [comment]
Also, @zbeekman, I'll be glad to help with the question of what was supported in Fortran 2008 vs Fortran 2015.  I just changed the name of this issue to make clear that it's a regression, albeit one that I wasn't aware of and one that was probably intentional because it relates to procedures that were refactored/replaced to support allocatable components inside derived type coarrays.  I knew the refactoring only provided partial support for the new feature being introduced.  I didn't know before this issue that the refactoring also broke existing functionality other than issue #292.  For that reason, I also just added this to the 2.0.0 release milestone, which has a due date of tomorrow so we'll have to push that date out.  We can talk about it during the OpenCoarrays call tomorrow.

**Comment by zbeekman** [comment]
OK, I missed @gutmann's link to his demo repo. This is EXTREMELY helpful. As a first step it is worth trying to reproduce on other systems (non-SGI/MPT etc.) to get a sense of  how universal this issue is and whether the problem is definitely in the library, etc. I think I'm clear RE F2008 vs 2015 additional parallel features.... I'll try to give it a shot somewhere else soon.

> but I think we all agree that introducing a regression in allocatable components of non-coarrays is very unfortunate regression that is likely to be a deal-breaker for a lot of users.

I don't think this is a regression. @gutmann said he's compiling with 6.3. This means we're building the old ABI for the GCC 6.3 interface. I *would* consider it a regression if older versions of OpenCoarrays before the allocatable component work started exhibit the same behavior.

Can someone try https://github.com/gutmann/caf_alloc_test on Cayenne with on Cayenne with an older version of OpenCoarrays? Looking back, to before allocatable components was added, would it be possible to try with https://github.com/sourceryinstitute/OpenCoarrays/releases/tag/1.7.4 on Cheyenne? It looks like the 1.7 series predate any work on allocatable components of coarray derived types.

**Comment by rouson** [comment]
@zbeekman You're right.  I confused this with issue #422 because the data structures involved in this issue have the same essential features. Issue #422, which _is_ a regression because issue #442 relates to functionality that worked in GCC 6 but is not yet supported in GCC 7.  I just undid my edit for the title of this issue, but I'll leave this issue as part of the 2.0.0 milestone. I'll instead add the regression label to issue #422.

**Comment by zbeekman** [comment]
It's worth trying an older 1.7 release, I'm not 100% sure how much of the
older code got touched vs how much just got wrapped in `#ifndef GCC7`....

**Comment by vehre** [comment]
Trying to catch up on this:
> @vehre, I just built OpenCoarrays 1.9.0-32-g7dbcf92 using GCC 7.1 and the non-developer tests of allocatable components pass:
>
>      Start  7: register_alloc_comp_1
> 7/43 Test  #7: register_alloc_comp_1 ............   Passed    0.09 sec
>      Start  8: register_alloc_comp_2
> 8/43 Test  #8: register_alloc_comp_2 ............   Passed    0.09 sec
>      Start  9: register_alloc_comp_3
> 9/43 Test  #9: register_alloc_comp_3 ............   Passed    0.09 sec
>      Start 10: async_comp_alloc
>10/43 Test #10: async_comp_alloc .................   Passed    0.14 sec

All of the above tests just allocate and check that the component is allocated (also remote). They do not access any data in the allocated component (neither local nor remote).

From ** gutmann commented 5 days ago **
> Agreed, that is what I meant by with allocatable data, but I guess you mean it is even more specific to allocatable components of derived types? While that is sort of a special case, it may also be one of the most common cases outside of simple tests programs (I think pretty much every piece of vaguely modern Fortran code I have written or used has used allocatable arrays that are components of a derived type as the core data structure)

It gets even more complicated. Let's look at all possible kinds of coarrays and what is supported in current gfortran and ocaf:

coarray kind | example | gfortran support | ocaf support
----------------|-------------|----------------------|------------------
global saved coarrays of intrinsic types | float, saved :: caf[*] | yes | yes
global allocatable coarrays of intrinsic types | float, allocatable :: caf[*] | yes | yes
coarrays of derived type w/o allocatable components | type(T), saved :: tcaf[*] ; type(T), allocatable :: t2caf[*] | yes | yes
coarrays *in* derived types (saved and allocatable) | type T ; float :: caf[*] ; end type T | yes | yes
allocatable components in derived type coarrays | type T ; float, allocatable :: acc ; end type T ; type(T), saved :: caf[*] | yes | wip *)
coarray get where the target needs to be implicitly allocated | float, allocatable :: target ; float, saved :: caf[*] ; target = caf[1] | yes | wip *)
coarray put or getput where the target needs to be implicitly allocated | float, allocatable :: source ; float, saved :: caf[*] ; caf[1] = source | yes | no

Sorry for the bad formating of the code in the table. I could not figure quickly how to get this right. But I hope you get the intention.

*) The work-in-progress is to support get() and put() operations on the allocatable component. My first proposal on this proved incomplete and non-functional. Therefore, no at the moment allocatable components are not supported by opencoarrays. Not even a simple get() on them will work reliably.

**Comment by vehre** [comment]
From  'rouson commented 5 days ago':
>  but I think we all agree that introducing a regression in allocatable components of non-coarrays is very unfortunate regression that is likely to be a deal-breaker for a lot of users.

As I do understand this issue we are talking about allocation speed on large clusters with gfortran 6.x. Gfortran 6.x does not have any support for allocatable components in derived type coarrays. Therefore there is no impact of the code added to support those. When the allocation is slow for gfortran 6.x, then I assume that the mpi implementation has an issue either in the MPI_Win_allocate () or in the routines used to sync() after the allocate. There is just one MPI_Win_allocate in the whole routine to allocate the coarray's data. I don't know how to further optimize that.
Taking a look at your example and computing what is going on:

nx * ny *nz * sizeof(real) * coarray1-9 * 9-times calling alloc_test
100 *1000* 30 * 4 * 9 * 9 = 972000000 bytes ~ 1 GB
Given that each node has 36 cores and assuming that you recieve all 36 cores of one node, each node needs to have at least 36 GB. Given that each node has at least 64 GB this should be sufficient as long as sizeof(real) really is 4 bytes on your system. When it is 8 bytes there is the fault!

Nevertheless does this look to me more like a memory management issue of the underlying mpi-library then one of opencoarrays, but I am open to other suggestions.

> Also, @zbeekman, I'll be glad to help with the question of what was supported in Fortran 2008 vs Fortran 2015. I just changed the name of this issue to make clear that it's a regression, albeit one that I wasn't aware of and one that was probably intentional because it relates to procedures that were refactored/replaced to support allocatable components inside derived type coarrays. I knew the refactoring only provided partial support for the new feature being introduced. I didn't know before this issue that the refactoring also broke existing functionality other than issue #292. For that reason, I also just added this to the 2.0.0 release milestone, which has a due date of tomorrow so we'll have to push that date out. We can talk about it during the OpenCoarrays call tomorrow.

For a gfortran 6.x the refactoring is not relevant. 6.x code was not changed for allocatable components of derived type coarrays, because 6.x does not support them (do not mix up with coarray *in* derived types. Their support is unchanged and present in 6.x).

**Comment by gutmann** [comment]
Thanks @vehre If this is a bug or issue in the MPI library, that would be good to know.  Do you have a simple MPI test case in mind that might help shed light on that?  I'd be happy to run it on Cheyenne.  

@rouson can you run with gfortran on swan?  If so, would you mind testing this example, or better the full coarray_icar with gfortran and a large number of image to see if the problem persists there?  I believe Brian has gfortran + opencoarrays running on one or both of their Crays, so maybe he can test coarray_icar with ~3000 images and see if it runs into similar problems with a different MPI library. 

**re: memory requirements**:  While you are right that this test code pushes the memory requirements a little (though reals are 4 bytes not 8), the bigger problem came when running coarray_icar.  In that case, coarray_icar was using a domain of ~1000 x 1000 x 20, but that domain was split over 3000+ images, so each image was only using a tiny fraction of memory (even with 36 on one node it isn't a problem.)  I'm fairly certain I could reduce the total memory requirements of this test case with a local domain of ~20x20 and still see problems on a very large number of images.

**Comment by vehre** [comment]
Well, first of all coarray-allocated memory is a keeper: Explicitly allocated memory for a coarray, needs to be deallocated, i.e., gfortran does not automatically/implicitly deallocate a coarray. The memory is simply lost, but never reported when you run your program with valgrind and check for memory leaks, because opencoarray cleans up on termination and keeps a list of all coarrays allocated.

Well, the testcase could be a C-code, that mimicks the behaviour of allocating a larger chunks of mpi_wins.

What we forget here is, how remote memory access is implemented: e.g. on a single machine "parallel" machine it is shared memory and nearly every address is possible for remote access. But one clusters that might not be true depending on the mpi-library. The library may simply run out of address-space, because of paging limitation or the like. Just a guess.

That C-test could look like this (note I had to add .txt, because github does not know C-files :-)):
[alloc_c_test.c.txt](https://github.com/sourceryinstitute/OpenCoarrays/files/1202515/alloc_c_test.c.txt)

This essentiall what your fortran program is doing. Maybe you can check with your mpi-library and shed some light, whether it is a mpi- or a coarray-issue.

**Comment by gutmann** [comment]
I'm fairly confident there are no memory leaks in the problematic code (in coarray_icar) as we are never expecting to deallocate memory.  All arrays (and coarrays) are allocated once at the beginning of the simulation and are used throughout, however it is the initial allocation that is problematic. It looks like your c-code test is (deliberately?) leaking memory, can we simply make mem be [81] elements long and index it inside the for loop, then check the timing of each loop?  (it may be that leaking memory does not effect this problem so it doesn't matter, I just want to check.) 

The concern with the fortran test case is not that the first allocate takes a long time, it is that the length of time required for an allocation increases with each successive allocation (though usually the very last allocation isn't the slowest).  

If the test case you posted runs on 3600 images in <10minutes, would you consider that evidence that the MPI library is not the problem? 

I'll see if I can try this C-code on cheyenne later today or tonight, note that I'll be on vacation for the following week, so if I don't get this done tonight, then it will be a little while before I can test it, but I will.

**Comment by gutmann** [comment]
I think we may have a winner... so far that alloc_c_test.c has not completed after >30 minutes on 3600 processes!  I'm going to see if I can simplifiy it a little more with, e.g. a smaller chunksize, then pass this on to our computing group.  I'll report back if/when I figure anything else out.  

I'll also see if I can get opencoarrays built with openmpi or mpich on cheyenne instead of the pre-built version that uses mpt (if they can't fix the "bug" in mpt).  

Also curious what you mean by github does not know C-files
e.g. https://github.com/torvalds/linux/blob/master/kernel/reboot.c looks fine.

**Comment by gutmann** [comment]
FYI, have tested this C-code on Cheyenne with alternate mpi libraries and achieved reasonable scaling characteristics, so I think we can pin this on mpt.  I've submitted a report to CISL, I'll update if I hear anything interesting, but we may be able to close this!

**Comment by zbeekman** [comment]
Ethan, I'm not shocked that there were issues in MPT. The FUN3D/NASA guys
had SGI engineers creating patches and installing hotfixes on Pleiades for
hosts of problems.

If you think this is definitive evidence that MPT is to blame (which
appears to be the case to me) then please close this issue. We can continue
discussing etc here even after it's closed.

Enjoy your vacation,
Best,
Zaak

**Comment by gutmann** [comment]
I'm pretty surprised, but I do consider this fairly definitive.  Closed.

**Comment by vehre** [comment]
Sorry for not responding earlier. I am German based (timezones and so on).
My intention with the memory leak was to simulate the small fortran test-code as closely as possible in C to expose issues of the opencoarrays handling. The intention was exactly what we learned: is it a mpt or a opencoarrays issue. With checking against mpich and openmpi you exactly figured what was the issue and the c-code was made exactly for this. Great job.

With " github does not know C-files" I meant, that when one attaches a file to one of these comments, the filename must not end on .c, but .txt, .pdf, .png or others.

Happy vacation.
