### ISSUE TITLE
Question: Shall we replace is_contiguous with CFI_is_contiguous?

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#568]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Question #

As fate would have it, within ~2 days of setting up the separate [ISO_Fortran_binding] repository, I discovered one reason we might instead keep the associated files in OpenCoarrays: Would it make sense to replace our [`is_contiguous`] function with the new standard-conforming [`CFI_is_contiguous`] that [ISO_Fortran_binding] provides? The OpenCoarrays [`is_contiguous`] function takes one argument of type [`gfc_descriptor_t`].  As of GCC 8, [`gfc_descriptor_t`] is standard-conforming and is therefore compatible the one [`CFI_cdesc_t`]-type argument of [`CFI_is_contiguous`].  See section 2.1 of "The new features of Fortran 2018" ([Reid, 2018]) for the standard specification of [`CFI_cdesc_t`].  If we do replace our function with standard one, it would be nice to ensure that users don't have to download the two projects separately or use git submodules.   If others agree, then it could make sense to keep [ISO_Fortran_binding] in OpenCoarrays.

@afanfa @zbeekman @dcelisgarza  Any thoughts?

[links]:#
[ISO_Fortran_binding]: https://github.com/sourceryinstitute/ISO_Fortran_binding
[`is_contiguous`]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/src/common/caf_auxiliary.c#L37
[`CFI_is_contiguous`]: 
https://github.com/sourceryinstitute/ISO_Fortran_binding/blob/master/src/ISO_Fortran_binding.c#L351
 [`gfc_descriptor_t`]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/src/libcaf-gfortran-descriptor.h#L62
[`CFI_cdesc_t`]: https://github.com/sourceryinstitute/ISO_Fortran_binding/blob/master/src/ISO_Fortran_binding.h#L72
[Reid, 2018]: https://www.lrz.de/services/software/programmierung/fortran/ISO-IECJTC1-SC22-WG5_N2145_Summary_of_Fortran_2018.pdf

**Comment by zbeekman** [comment]
I really like the idea of adopting `CFI_is_contiguous` once ISO_Fortran_binding compiles cleanly and portably with C compilers and doesn't use any "bad habbits" or GNU extensions. These anti-features would likely inhibit the adoption by compiler vendors and package maintainers alike.

In addition, I think it will greatly reduce complexity and increase flexibility to *keep ISO_Fortran_binding as a __separate__ project*. If we really always want it in OpenCoarrays, then we should either:

1. Get GFortran to adopt it ASAP, and then it will get installed as part of the compiler, because the code is tightly linked to the compiler to begin with
2. Use a git submodule (It is trivial to package the release tarball to include the ISO_Fortran binding sources)
3. Use CMake's `ExternalProject` module to drive the download and configuration of ISO_Fortran_binding.

The purposes and uses of the libraries are sufficiently distinct that I think it's cleaner and a better separation of concerns to keep them as two separate projects. I think the concerns about pre-requisites are still easily circumvented with the approaches I proposed if we want to adopt and implement `CFI_is_contiguous` instead of `is_contiguous`.

In addition it gives us a chance to use some improved CMake best practices and stylistic choices in ISO_Fortran_binding, rather than carrying along our technical debt from OpenCoarrays and having that affect ISO_Fortran_binding.

I'm open to be persuaded to the contrary, but as it stands I have a rather strong preference for maintaining a separate repo and project for ISO_Fortran binding, whether or not we choose to use it in OpenCoarrays.

**Comment by zbeekman** [comment]
@rouson If you want to talk with Sorren and Salvatore about this tomorrow let me know. I don't have much time to spare but I could probably make some time in the morning.

**Comment by zbeekman** [comment]
Yes that makes sense. I like option 2 better than 3, however, because it
reduces complexity on our end. I think we should only concern ourselves
with two types of users: the helpless/uninitiated and the modestly
competent. I don’t think it’s too much to ask to say “Your options are to
install from an official release or learn how to use git with submodules”.
Trying to support a middle ground will place too much of a burden on our
precious time, IMO.

**Comment by zbeekman** [comment]
If we keep it open let's change it to an RFE.

**Comment by zbeekman** [comment]
Actually let's close and create a new RFE tracking this.
