### ISSUE TITLE
Question: If building OC from source, what is the proper invocation of the compiler?

### ISSUE THREAD

**Issue by arjenmarkus** [sourceryinstitute/OpenCoarrays#577]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

Please make sure to put any logs, terminal output, or code in
[fenced code blocks]. Please also read the [contributing guidelines]
before submitting a new issue.

# Question #

I downloaded the source code and built the package using CMake and make. This was no problem. But when I tried to build a "hello, world" program, it was unclear how I should do that. The Fortran compiler on the virtual machine, gfortran, version 7.3.0, explicitly required libraries. 

The "caf" command the documentation referred to did not exist, but the shell informed me that a package "open-coarrays-bin" was available for download.

As I am writing this up, it may be that I forgot to run "make install". 

My question boils down to: could you add the name of the Open Coarrays package or packages to the information. I had trouble finding it before I typed in "caf hello.f90". That was the reason I tried building it from source.

Sorry to bother you with such a foolish and simple question.

[links]:#
[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com
[fenced codeblocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[GFortran bug tracker]: https://gcc.gnu.org/bugzilla/
[Intel MPI]: https://software.intel.com/en-us/intel-mpi-library
[MPT]: http://www.sgi.com/products/software/sps.html
[MVAPICH]: http://mvapich.cse.ohio-state.edu
[MPICH]: https://www.mpich.org
[Open-MPI]: https://www.open-mpi.org
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[official release]: https://github.com/sourceryinstitute/OpenCoarrays/releases
[CMake install]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#cmake-scripts
[homebrew]: https://brew.sh
[issues page]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[mailing list]: https://groups.google.com/forum/#!forum/opencoarrays
[install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/install.sh

**Comment by uihsnv** [comment]
For the 'cmake-make' way of installing, it does look like you have to specify the links. I use this:
```
$ /opt/mpich/bin/mpifort -fcoarray=lib <filename.f90> -lcaf_mpi
$ /opt/mpich/bin/mpirun -n <num_images> ./a.out
```

**Comment by arjenmarkus** [comment]
Ah, thanks - I thought it was something like that, but I could not find the
proper invocation.

Regards,

Arjen

2018-08-14 18:56 GMT+02:00 Vishnu V K <notifications@github.com>:

**Comment by zbeekman** [comment]
Hi @arjenmarkus!

It would help to know what operating system you are on, and to include the information from the [bug report section](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/.github/ISSUE_TEMPLATE.md#defectbug-report) of the issue template.

I'm not sure I completely understand your question.

> As I am writing this up, it may be that I forgot to run "make install".

OpenCoarrays comes with two wrapper scripts, similar to MPI. One for compilation, and one for running the compiled coarray code. These scripts are named `caf` and `cafrun` and get installed into the `bin` dir of the installation tree. If you are building directly with CMake followed by make (my preferred method) then the developer/quickstart instructions at https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL outline this process fairly well. If you specify `-DCMAKE_INSTALL_PREFIX=/some/non/standard/path` then please ensure that `/some/non/standard/path/bin` is in your `$PATH` so that your shell can find `caf` and `cafrun`. `make install` is a critical part of the installation process to ensure that you can just type `caf` or `cafrun` without a full path. If you don't sed `-DCMAKE_INSTALL_PREFIX=...` then this should install into a system-wide location such as `/usr/local`. This approach will likely require you to have elevated permissions when you run `make install` (e.g., `sudo make install`).

> My question boils down to: could you add the name of the Open Coarrays package or packages to the information. I had trouble finding it before I typed in "caf hello.f90". That was the reason I tried building it from source.

I don't understand this question. What do you mean by "the information". And what do you mean by the OpenCoarrays package or packages?

> The "caf" command the documentation referred to did not exist, but the shell informed me that a package "open-coarrays-bin" was available for download.

We do not package OpenCoarrays in various OS distribution's package managers. Some OSes like Arch Linux, Ubuntu, FreeBSD, and macOS (via Homebrew) do provide OpenCoarrays packages. These are maintained by the package maintainers for those OS distributions. We have no control over the packaging ourselves, so if you find the process of installing from package management to be unsatisfactory, then please report that to the OS/Package maintainers.


@uihsnv said:
> For the 'cmake-make' way of installing, it does look like you have to specify the links. I use this:
> 
> $ /opt/mpich/bin/mpifort -fcoarray=lib <filename.f90> -lcaf_mpi
> $ /opt/mpich/bin/mpirun -n <num_images> ./a.out

I'm not sure what to make of this. If you have the `caf` and `cafrun` scripts installed and on your path, then you can use them instead of explicitly passing flags to the mpifort/mpif90. It is possible that package maintainers only choose to install portions of OpenCoarrays (i.e. just the main library) or that they split the assets into different packages like `opencoarrays-dev` for module files, header files and libraries and `opencoarrays-binary` or something for `caf` and `cafrun` scripts (although this is dumb, IMO, but they might be doing this). If you install via package management and there is no option for installing the compiler wrapper script and the job launcher script, then you will have to explicitly pass the libraries and extra command line flags to the underlying MPI/GFortran commands yourself, as @uihsnv shows above.

@arjenmarkus if you're installing from source yourself, and having trouble calling CMake and make directly, the `install.sh` script tries to verify all prerequisites are installed, and then build OpenCoarrays and provides some instructions for setting up your environment after success. By default it will install missing prerequisites and install everything into the `prerequisites/installations` folder in the source tree, so you don't need sudo privileges.

I hope my response helps, and that you are able to install and experiment with OpenCoarrays successfully.

Thanks,
Zaak

**Comment by uihsnv** [comment]
@zbeekman https://groups.google.com/d/msg/opencoarrays/uRlWSby8dY8/f44hxeQsBwAJ

**Comment by uihsnv** [comment]
Done. https://github.com/sourceryinstitute/OpenCoarrays/issues/579

**Comment by zbeekman** [comment]
@arjenmarkus Is this issue sufficiently resolved for you? Can we close this ticket?

**Comment by arjenmarkus** [comment]
Sure, the main reason for putting in this question was my own incompetence
with package managers and package repositories. I assume I am not the only
one suffering from this and it would of course be very nice to be guided
along without having to hunt for information. But I quite understand that
you have no control over the way Linux distributions organise their
packages (I noticed the -bin and -devel versions - hardly necessary, I'd
say, and only confusing)

If I come around to it, I may try and suggest some changes to the
installation document to make such things clearer for people who, like me,
get confused by package managers :).

Regards,

Arjen

2018-08-16 22:35 GMT+02:00 zbeekman <notifications@github.com>:

**Comment by uihsnv** [comment]
@arjenmarkus What distro are you on? As far as packaging is concerned, typically, `-bin` packages have the binaries, and `-devel` ones have the header files. Since OpenCoarrays is meant part of a compilation process (for whatever fortran code you're compiling), I'm guessing you need both.

**Comment by arjenmarkus** [comment]
I am using Lubuntu on this virtual machine. You are probably right: to use
OC you need both. But I do not quite see the rationale behind this
dichotomy - it is not a matter of disk space, so why not put everything in
one package? Just complaints from a grumpy old man ;).

Regards,

Arjen

2018-08-17 11:27 GMT+02:00 Vishnu V K <notifications@github.com>:

**Comment by rouson** [comment]
@uihsnv Thanks for explaining that. For some time, I've been wondering about the bewildering way in which Linux package managers name packages (e.g., not sure who decided to put a hyphen in the APT `open-coarrays` package) and I couldn't figure out why I seemed to need the `-devel` version for every package I've ever installed.  Now at least one mystery is solved!

**Comment by arjenmarkus** [comment]
:) I guess I am not the only one puzzled by this.

Regards,

Arjen

2018-08-17 16:14 GMT+02:00 Damian Rouson <notifications@github.com>:

**Comment by zbeekman** [comment]
Honestly, building from source is usually quick and fairly straightforward. Also, currently there is only 2.0.0-RC1-2 in Ubuntu, AFAICT, so you will also get more up-to-date software if you build from source. But I guess this also requires you to know about the package manager to get the right version of GCC etc... You can use install.sh to compile your own MPICH and GCC, however, that will indeed take some time.

I'm going to close this. Feel free to open an issue with recommendations for improved language in INSTALL and INSTALL.md
