### ISSUE TITLE
Defect: Test 14 (alloc_comp_get_convert_nums) gets stuck

### ISSUE THREAD

**Issue by arjenmarkus** [sourceryinstitute/OpenCoarrays#578]
Please make sure to put any logs, terminal output, or code in
[fenced code blocks]. Please also read the [contributing guidelines]
before submitting a new issue.

# Defect/Bug Report #
I have built Open Coarrays version 2.2.0 on a virtual machine. This was successful, but running "make test" gets stuck in test no. 14 - alloc_com_get_convert_nums. While I do not know how long it should take, I have left it running for at least half an hour before I decided it would not work.

- OpenCoarrays Version: 2.2.0 
- Fortran Compiler: gfortran 7.3.0 
- C compiler used for building lib: gcc 7.3.0
- Installation method: none - running "make test"
- Output of `uname -a`: Linux markus-VirtualBox 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- MPI library being used: OpenMPI 2.1.1-8
- Machine architecture and number of physical cores: Intel 64 bits, 8 cores
- Version of CMake: 

## Observed Behavior ##
The test no. 14 starts, but does not finish in a reasonable time

## Expected Behavior ##
The test starts and runs in a similar time as the others and after that all other tests are run to completion

## Steps to Reproduce ##
Run "make test"

[links]:#
[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com
[fenced codeblocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[GFortran bug tracker]: https://gcc.gnu.org/bugzilla/
[Intel MPI]: https://software.intel.com/en-us/intel-mpi-library
[MPT]: http://www.sgi.com/products/software/sps.html
[MVAPICH]: http://mvapich.cse.ohio-state.edu
[MPICH]: https://www.mpich.org
[Open-MPI]: https://www.open-mpi.org
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[official release]: https://github.com/sourceryinstitute/OpenCoarrays/releases
[CMake install]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#cmake-scripts
[homebrew]: https://brew.sh
[issues page]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[mailing list]: https://groups.google.com/forum/#!forum/opencoarrays
[install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/install.sh

**Comment by arjenmarkus** [comment]
I am not sure how to find out how many cores are actually used by the VM.
Oh, just found that - there is a single CPU (out of the eight available)
assigned to the box. I ran a very simple test (hello, world) with -np 40
within that same box. No problem, but of course they were not dependent on
each other.

Just tested with 8 cores assigned: that makes no difference - test 14 still
hangs.

OpenMPI 2.x was the package I found. Perhaps I should try to find that
newer series.

Regards,

Arjen

2018-08-15 19:23 GMT+02:00 zbeekman <notifications@github.com>:

**Comment by zbeekman** [comment]
It's likely that some tests will fail when severely oversubscribed with certain MPI implementations. You can allocate more cores to the machine in Virtualbox: 

1. Open VirtualBox
2. Select VM
3. Press the settings gear icon
4. Click the system tab
5. Click the processor sub-menu/tab
6. Slide the number of CPUs up to a higher value

<img width="763" alt="screenshot 2018-08-16 11 25 48" src="https://user-images.githubusercontent.com/279612/44218215-3ba1a780-a147-11e8-8f90-4efd6075e938.png">

This might not resolve the issue though. It might be a bug in OC or it may be due to an older OpenMPI.

I think the `cafrun` launcher script automatically passes `--oversubscribe` to `mpiexec`/`mpirun` but if not you can add it yourself `cafrun -np 8 --oversubscribe ./a.out`. You can also check what would be invoked with the `-s` or `--show` option to verify that the correct arguments are passed to the MPI launcher:

```
cafrun --show -np 4 ./a.out
```

**Comment by arjenmarkus** [comment]
Hm, I have experimented with these options:
- --show simply shows the command passed to mpirun
- Only if I add --oversubscribe explicitly, does it show up with --show
- I first put --oversubscribe _before_ the -np 4, but then the program does
not run at all

I had the test program run once with 3 images, but that must have been a
lucky coincidence, as I cannot repeat it.

The current settings are such that the virtual machine uses three cores.

Regards,

Arjen

2018-08-16 17:30 GMT+02:00 zbeekman <notifications@github.com>:

**Comment by arjenmarkus** [comment]
As an experiment: it seems I can indeed get MPICH3 for this virtual
machine. If I install that, how can I verify that that MPI version is used?

Regards,

Arjen

2018-08-17 10:42 GMT+02:00 Arjen Markus <arjen.markus895@gmail.com>:

**Comment by zbeekman** [comment]
> Hm, I have experimented with these options:
> - --show simply shows the command passed to mpirun
> - Only if I add --oversubscribe explicitly, does it show up with --show
> - I first put --oversubscribe _before_ the -np 4, but then the program does
> not run at all

These are all intended behaviors, however, the last one is a bug #467, currently the argument parsing is very bad. This has been on my todo list to fix for some time, but this is a volunteer project for me, so, I'm not sure when it will get done.

> I had the test program run once with 3 images, but that must have been a
> lucky coincidence, as I cannot repeat it.

I'm guessing this is an OpenMPI issue.

> As an experiment: it seems I can indeed get MPICH3 for this virtual
> machine. If I install that, how can I verify that that MPI version is used?

Well, how are you installing open-coarrays? If you are doing it through package management, i.e., `sudo apt-get install open-coarrays-bin ...` then it will be built against whichever MPI distribution the package maintainers choose. (Usually they pick OpenMPI and build everything with that.) That way users can link against multiple MPI libraries.

I would recommend building from source if you want to use MPICH. If you can uninstall OpenMPI or at least remove it from your PATH and environment variables (like `MPI_HOME`), install MPICH and make sure it *IS* on your $PATH, then you can follow the instructions in [INSTALL](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL) for a quick and easy build. (You will need CMake, binaries for linux can be gotten from http://www.cmake.org/download or through your package manager (`sudo apt install cmake-bin cmake-data` or something like that)

**Comment by zbeekman** [comment]
Hi @arjenmarkus,

I can't reproduce this, at least not with the latest version of OpenCoarrays and OpenMPI and MPICH, with GFortran 8.3.

It is possible that if you only have one processor allocated to your VM that certain MPI distributions can't make progress and will lock up: Process one sits waiting for process two, but the OS/MPI implementation never allows process 2 (running on the same core) to make any progress and send a message/ack.

Something in the latest tooling with OpenMPI 4.0.0 breaks three OpenCoarrays tests. I think theses are bugs in OpenMPI.

```
The following tests FAILED:
         14 - alloc_comp_get_convert_nums (Failed)
         23 - alloc_comp_send_convert_nums (Failed)
         69 - issue-515-mimic-mpi-gatherv (Failed)
```

Since I cannot reproduce the issue, and I suspect this is particular to running with only 1 core in combination with a particular MPI distribution.

As I mentioned above, beyond allocating more cores and/or switching MPI implementations, with OpenMPI you should pass `--oversubscribe` __*after*__ `-np 4`:

```
cafrun -np 4 --oversubscribe ./alloc_comp_get_convert_nums
```

when using OpenMPI.
