### ISSUE TITLE
Question: what is meant by non-OpenCoarrays-aware compilers?

### ISSUE THREAD

**Issue by arjenmarkus** [sourceryinstitute/OpenCoarrays#582]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Question #

The file "INSTALL.md" contains a sentence about the .mod file whic should be useful for "non-OpenCoarrays-aware compilers". This is slightly confusing: I presume that this has to do with plain invocations of the gfortran compiler and not with arbitrary compilers?

FWIW, I took the liberty of attaching a small patch file (renamed to .txt) for a handful of typos and the like in the INSTALL and INSTALL.md file. Feel free to apply in whole or partly or not at all.

[0001-Correct-a-few-typos-and-double-words-as-well-as-some.txt](https://github.com/sourceryinstitute/OpenCoarrays/files/2309229/0001-Correct-a-few-typos-and-double-words-as-well-as-some.txt)

[links]:#
[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com
[fenced codeblocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[GFortran bug tracker]: https://gcc.gnu.org/bugzilla/
[Intel MPI]: https://software.intel.com/en-us/intel-mpi-library
[MPT]: http://www.sgi.com/products/software/sps.html
[MVAPICH]: http://mvapich.cse.ohio-state.edu
[MPICH]: https://www.mpich.org
[Open-MPI]: https://www.open-mpi.org
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md
[Helping Out]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md#helping-out
[official release]: https://github.com/sourceryinstitute/OpenCoarrays/releases
[CMake install]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#cmake-scripts
[homebrew]: https://brew.sh
[issues page]: https://github.com/sourceryinstitute/OpenCoarrays/issues
[mailing list]: https://groups.google.com/forum/#!forum/opencoarrays
[install.sh]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/install.sh

**Comment by zbeekman** [comment]
> The file "INSTALL.md" contains a sentence about the .mod file whic should be useful for "non-OpenCoarrays-aware compilers". This is slightly confusing: I presume that this has to do with plain invocations of the gfortran compiler and not with arbitrary compilers?

Yes, we need a better definition of what this means. Essentially, in practice, for now, it means a recent enough version of GFortran (starting with 5.something). A more generic and abstract definition of OpenCoarrays aware (OCA for short) compiler is one that will generate compatible (API & ABI) calls into a runtime library (whose interface matches OpenCoarrays) to handle Coarray allocation, communication, etc.

We have some crude scripts that can perform some translation (regexp based, **NOT** a robust parsing and generation from an AST) of the most basic coarray syntax into direct library calls. The OpenCoarrays module also defines some collectives and other procedures that can be used with any modern enough Fortran compiler, whether or not it supports coarrays at all, or a non OpenCoarrays implementation (e.g., Intel). This can give you access to coarray collectives etc. from compilers which do not yet support them; they basically just wrap certain MPI calls.

> FWIW, I took the liberty of attaching a small patch file (renamed to .txt) for a handful of typos and the like in the INSTALL and INSTALL.md file. Feel free to apply in whole or partly or not at all.

Thanks so much for the patch! FYI, the easiest way to contribute to OpenCoarrays is through opening up a pull request. However, we welcome and accept any and all helpful contributions! I'll take a look at your patch, and will probably apply it.

I hope I've answered your question satisfactorily. If not, please let me know. Otherwise, I'll plan to close this ticket once I've merged your patch.

**Comment by arjenmarkus** [comment]
Hi Zaak,

thanks for that explanation. IIUIC, OpenCoarrays ought to be more widely
useable than "merely" gfortran. That is nice to know. I have stared a bit
at the source code, but I could not quite get the hang of it ;).

As for pull requests, not sure how to do that. My use of git is very very
basic.

Regards,

Arjen

Op ma 27 aug. 2018 om 16:55 schreef zbeekman <notifications@github.com>:

**Comment by zbeekman** [comment]
@arjenmarkus: I've applied your patches to the documentation. I'm closing this ticket. Feel free to reopen it if you feel it has not been adequately addressed.
