### ISSUE TITLE
CAF creating bad code when gfortran is fine

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#597]
[CAF_test.zip](https://github.com/sourceryinstitute/OpenCoarrays/files/2484626/CAF_test.zip)

Downloaded the latest VirtualBox machine (today) and have a "simple" program (hzetrn_trn.f90) that works fine when compiled by gfortran but does not work when compiled by caf.  Unzip above and get to a tcsh then % source go.csh.  This compiles the gfortran and caf codes and runs them.  The first one (gfortran) completes and has lots of output.  The second one has a segfault and a traceback.

This program uses an unlimited polymorphic pointer with Select Type structure to keep the I/O calls to one set of basic routines (Read_Write_Basic_Mod and the Type_<user defined type>_Mod).  The purpose is to keep the Fortran 77 programmer away from the guts of I/O algorithm and allow them to just create the Read_Write_<item>_Mod routine which is simple and almost like Fortran 77 programming.  This is illustrated by the Read_Write_TRNINPUT_Mod and the Type_CArray_1D_Mod routines.  The expert creates the Type<user defined type>_Mod and the Fortran 77 programmer creates the Read_Write_TRNINPUT_Mod routine.  This also leaves the main routine with no pointers and just allocatable arrays since the physics of the program (not here) is Fortran 77.

**Comment by rouson** [comment]
Thanks for reducing this and addressing some of the safety issues around pointers.  At a minimum,  this exercise has eliminated `co_broadcast` as the culprit so that's progress!  To get closer to a tightly focused demonstration of the issue, it would greatly help if you could

-[ ] Add a test that demonstrates what is expected, e.g., something of the form `if (expected_result /= actual_result) error stop "Test failed."`
-[ ] Reduce the size of the code to no more than 100 lines in one file.  If it really is a compiler error, it would be extremely rare to require more lines than that to demonstrate.  I've submitted hundreds of bug reports on at least a half-dozen compilers and I can only recall once or twice needing more than a few tens of lines to demonstrate the bug.
-[ ] Run the executable with [valgrind] to check issues with pointers.  It's very easy to get memory accesses incorrect with pointers and the resulting problems can be unpredictable because you can accidentally overwrite a memory location and the behavior can change depending on the operating environment, compiler version, or any number of other factors.

Some ways to reduce the code:
1. Remove blank lines.
2. Remove comments unless they relate to the bug you're demonstrating.
3. Choose one problematic value that is believed to be evidence of a bug and then remove all code that does not impact that value.
4. Collapse everything to one file.
5. Combine all module procedures and module variables into one module or, better still, move all variables into the main program and move all procedures from modules into a `contains` block in the main program.

These are just a few ideas.  There could be a lot more that can be done.  Admittedly, the process can take several hours or more, but if the submitter doesn't do take these steps, then it's invariably the very first thing the compiler developer or OpenCoarrays developer is likely to take in order to crystallize the issue. Given that there appears to be no use of parallel features in the submitted code, it's unclear how this could be a problem with OpenCoarrays. 

I'm open to an interactive discussion offline if that would be helpful.   I am especially curious about the reasons for using pointers of intrinsic type such as
```
Integer, Pointer, Dimension(:) :: lower_p, upper_p
```
and I'm also curious about the motivation for using unlimited polymorphism.  If pointers can be avoided, it will _greatly_ reduce the chance of programmer error.

Just to provide some context for my suggestions, I've been involved in submitting hundreds of bugs across a half-dozen compilers over the span of at least 15 years and I can only recall once or twice that I couldn't demonstrate the compiler bug in a few tens of lines (usually fewer than 25). 

[valgrind]: http://valgrind.org

**Comment by rouson** [comment]
Also, it appears that the pointers listed in my previous comment are being used to allocate memory:
```
Allocate ( D%lower_p(d%Dimen), D%upper_p(d%Dimen), stat=IOSTAT, errmsg=IOMSG )
```
I suspect this is a holdover from Fortran 95, which did not allow allocatable components in derived types.  Fortran 2003 made it possible to have derived types with allocatable components.   If I'm interpreting the code correctly, it appears the above pointers are never used in a pointer assignment such as `D%lower_p => foo`.  If so, I _strongly_ advice changing `pointer` to `allocatable` in the definition.  In addition to eliminating several potential problems, it might also simplify the code (e.g., if you can then replace the explicit allocation with an implicit allocation in an assignment).

**Comment by singleterry** [comment]
Hello,

I am not sure the Intel compiler was fully 2003 compliant when I wrote this part of the code.  I will see what I can do!!!

Thanks
Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by singleterry** [comment]
[CAF_test.zip](https://github.com/sourceryinstitute/OpenCoarrays/files/2485236/CAF_test.zip)

OK.  I have gotten rid of all pointers for the TRNINPUT part of the read (ignoring the TM_Read for now).

The  Type_CArray_1D_Mod works great.
The Read_Write_Basic_Mod works great.
The Read_Write_TRNINPUT_Mod does not - SEGFAULT.

% source go.csh

gives a 0 and a segfault in the gfortran version.  I am clearly misunderstanding what I am doing.  Plus, THE STANDARD has changed will doing this coding (over years) along with the Intel Fortran compiler and what it supports (my compiler during the development of this code).

Again, any suggestions (understand its for free here!) would be helpful.

**Comment by singleterry** [comment]
Hello,

I will work on this tomorrow!!!

Thanks again!!!

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by rouson** [comment]
@singleterry For now, let's move this discussion to the following temporary repository where I've eliminated another 200 lines of code: https://github.com/sourceryinstitute/quarantine

**Comment by rouson** [comment]
@singleterry I think [issue 1] on the quarantine repository identifies this as a bug in the submitted code so I'm going to close this issue.  Please feel free to reopen it if you disagree.

[issue 1]: https://github.com/sourceryinstitute/quarantine/issues/1

**Comment by rouson** [comment]
@singleterry Upon further reflection, I believe you did in fact find a compiler bug.  I've reduced the code even further, will submit the reduced case to the gfortran developers, and will cc you and Eric when I do.  Nonetheless, I'm glad we found a workaround.

**Comment by rouson** [comment]
This has been submitted as gfortran [Bug 87659](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87659).
