### ISSUE TITLE
Relocatable installation issue - again.

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#677]
Hello,

Thought this was tested, but had issues.  The caf script in 

prerequisites/installations/opencoarrays/2.7.0/bin

has a hardcoded link to the directory where opencoarrays was installed for gfortran.  This isn't relocatable.

Like I said, I thought I had checked it by renaming the original build directory but apparently that wasn't enough....  I will check much more thoroughly after this fix!!!!

Robert

**Comment by zbeekman** [comment]
@singleterry can you please copy the line in question with ~ 4 lines of surrounding context from `prerequisites/installations/opencoarrays/2.7.0/bin/caf`?

**Comment by zbeekman** [comment]
@singleterry: Also, __please use the issue template__, it's there for a reason. This is [not the first](https://github.com/sourceryinstitute/OpenCoarrays/issues/607#issue-378803015) [time](https://github.com/sourceryinstitute/OpenCoarrays/issues/606#issue-378754800) I have [needed further clarification](https://github.com/sourceryinstitute/OpenCoarrays/issues/607#issuecomment-437161213). We can't help you effectively without this.

After reviewing the generated caf script, I can't figure out what the issue you're encountering is.

I suspect that you might be building and installing with `./install.sh` (but I have no way of knowing because you didn't provide the information requested in the template).

I also suspect that you might be under the impression one of the following are true:

1. You can move just the `caf` script from it's installed location and leave everything else, or
2. You can copy the stuff from the `prerequisites` folder to a new location, or
3. Running `caf --show` you see the current location of the open coarrays library and include directory listed as an absolute path and assume that it won't update or display the correct paths after re-location.

These assumptions are incorrect (as far as I am aware). To address each one in turn:

1. The relative path between the wrapper scripts and the `bin`, `lib`, `lib64`, `include` etc. directories must be preserved. The directory structure must remain intact, but the root may change:
```
<prefix>/
├── bin
│   ├── caf
│   └── cafrun
├── include
│   ├── OpenCoarrays-2.7.1-38-g90cfb59_GNU-9.2.0
│   │   └── opencoarrays.mod
│   ├── libcaf-gfortran-descriptor.h
│   ├── libcaf-version-def.h
│   ├── libcaf.h
│   └── opencoarrays.mod
├── lib
│   ├── cmake
│   │   └── opencoarrays
│   │       ├── OpenCoarraysConfig.cmake
│   │       ├── OpenCoarraysConfigVersion.cmake
│   │       ├── OpenCoarraysTargets-release.cmake
│   │       └── OpenCoarraysTargets.cmake
│   ├── libcaf_mpi.3.dylib
│   ├── libcaf_mpi.a
│   ├── libcaf_mpi.dylib
│   └── libopencoarrays_mod.a
└── share
    ├── man
    │   └── man1
    │       ├── caf.1
    │       └── cafrun.1
    └── opencoarrays
        └── install_manifest.SHA256.txt
```
2. Large software packages like GCC and MPICH are not, in general, relocatable, and making them relocatable would be a large undertaking, well outside of the scope of OpenCoarrays. (@rouson do you know if you can specify install directories on a package-by-package basis using the script? If so then the solution is to install MPICH & GCC into their final locations before attempting to build OpenCoarrays.) Furthermore, Fortran compiler ABIs are not portable, sometimes even between major releases from the same vendor. We intentionally wish to keep the installed OpenCoarrays locked to the Fortran compiler and MPI library used to build it. Since OpenCoarrays is not responsible for being able to relocate these, then the paths to the Fortran compiler and MPI library are effectively frozen at configure time.
3. When I say OpenCoarrays is relocatable, what I mean is that if you build it with:
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/OpenCoarrays-x.y.z <path/to/source>
make install
```
then you can, for example,
```
mv /opt/OpenCoarrays-x.y.z ~/.local/OpenCoarrays
export PATH=~/.local/OpenCoarrays/bin:$PATH
which caf # ~/.local/OpenCoarrays/bin/caf
caf -o caf_ex coarray_example.f90
cafrun -n 4 caf_ex
```
Running `caf --show` now says something like:
```
/usr/local/bin/gfortran -I/Users/ibeekman/.local/opencoarrays/include/OpenCoarrays-2.7.1-38-g90cfb59_GNU-9.2.0 -fcoarray=lib -Wl,-flat_namespace -Wl,-commons,use_dylibs -L/usr/local/Cellar/libevent/2.1.11_1/lib ${@} /Users/ibeekman/.local/opencoarrays/lib/libcaf_mpi.a /usr/local/Cellar/open-mpi/4.0.1_2/lib/libmpi_usempif08.dylib /usr/local/Cellar/open-mpi/4.0.1_2/lib/libmpi_usempi_ignore_tkr.dylib /usr/local/Cellar/open-mpi/4.0.1_2/lib/libmpi_mpifh.dylib /usr/local/Cellar/open-mpi/4.0.1_2/lib/libmpi.dylib
```
even though it was built in `~/Sandbox/OpenCoarrays/build`, and originally installed into `/usr/local/Cellar/opencoarrays/x.y.z`

**Comment by singleterry** [comment]
If GCC and MPICH are not relocatable, then we are done.  I want to build the entire system within my account (/users0/rsinglet/CAF/opencoarrays/....) with the ./install.sh command and then copy to another place (from before to /usr/local/opencoarrays/....) with system privilege, visible on all nodes, etc....

This sounds like it is not doable because of the non-relocation ability of GCC/MPICH and NOT opencoarrays.

Therefore, if I want all packages (in a single directory structure), it sounds like I have to build it within /usr/local/OpenCoarrays so that caf and cafrun point to the proper places, the gfortran command and the mpiexec command work properly.

For the caf file (search below for rsinglet)

caf_version='2.7.1-8-g2dc92d1' # fetched from `git describe` and/or
# `.VERSION` file
oca_compiler="true" # True for GFortran > 5.0.0

# Compiler used to build OpenCoarrays; runtime must match compiler used during build
cafc="/users0/rsinglet/CAF/opencoarrays/prerequisites/installations/gnu/10.0.0/bin/gfortran"
if [[ "${cafc}" == @*@ ]]; then
  cafc=gfortran
fi
caf_mod_dir="include/OpenCoarrays-2.7.1-8-g2dc92d1_GNU-10.0.0"    # location of extensions module, needed for non-OCA compilers
mod_dir_flag="-I"


# Ideally these should be absolute paths. Since they are array
# variables multiple libs (absolute or not) can be specified provided
# proper quoting is used, when  is expanded. (i.e., expands with
# double quotes around each library w/path to ensure proper word
# splittling for paths with spaces) Handling of paths is complex
# between CMake and pkg-config: pkg-config (new enough versions) will
# theoretically expand paths with spaces escaped or the path
# quoted. CMake handles spaces in paths natively, but also sort of
# punts by making ; a field separator... So long story short,
# pkg-config output *should* __ALREADY__ handle word splitting, and
# variables expanded from CMake should be appropriately quoted.

# shellcheck disable=SC2054
mpi_link_flags=(-Wl,-rpath -Wl,/users0/rsinglet/CAF/opencoarrays/prerequisites/installations/mpich/3.2/lib -Wl,--enable-new-dtags) # e.g. `pkg-config
# --libs-only-other mpich`
# __*AND*__ `pkg-config
# --libs-only-L`
mpi_compile_flags=()
caf_libs=(lib64/libcaf_mpi.a) # e.g. "libcaf_mpi" "libcaf_extensions",
# preferably full paths, but could be
# combination of -L... and -lcaf_mpi...
mpi_libs=("/users0/rsinglet/CAF/opencoarrays/prerequisites/installations/mpich/3.2/lib/libmpifort.so" "/users0/rsinglet/CAF/opencoarrays/prerequisites/installations/mpich/3.2/lib/libmpi.so") # e.g. `pkg-config --libs-only-l` or full paths
# to MPI libs


For the cafrun file (again, search for rsinglet):

#---------------------
# Configured variables
#---------------------
#
# CAF_VERSION, MPIEXEC, MPIEXEC_NUMPROC_FLAG, MPIEXEC_PREFLAGS, MPIEXEC_POSTFLAGS,
# HAVE_FAILED_IMG
#

caf_version='2.7.1-8-g2dc92d1'
CAFRUN="/users0/rsinglet/CAF/opencoarrays/prerequisites/installations/mpich/3.2/bin/mpiexec"
if [[ "${CAFRUN}" == @*@ ]]; then
  CAFRUN=mpiexec
fi
have_failed_img=false
if [[ ${have_failed_img} == @*@ ]]; then
  have_failed_img=false
fi
numproc_flag='-n'
if [[ ${numproc_flag} == @*@ ]]; then
  numproc_flag='-np'
fi
preflags=""
preflags="${preflags//;/ }"
if [[ "${preflags}" == @*@ ]]; then
  unset preflags
fi
postflags=""
postflags="${postflags//;/ }"
if [[ "${postflags}" == @*@ ]]; then
  unset postflags
fi
#-------------------------
# End configured variables
#-------------------------

**Comment by zbeekman** [comment]
@singleterry You can ask @rouson for support/advice for what to do about MPICH and GCC. For system level installations, `install.sh` may not be the right tool to use. It's mostly there to baby users who are not used to building software like GCC from source, and allow them to get setup from their home directories on HPC systems, but making it deal with relocation of other software may be a bridge too far.

To see if it's even worth looking into, I recommend you perform the following experiments and report back:

1.Try moving only GCC to the desired location, and seeing if it works after relocation by compiling and then running a Fortran program. I suspect that the compiler, when used without `caf` and `cafrun` will fail in this case. I would be happy to be wrong, however.
2. If the compiler *DOES* work, then the next step is try moving MPICH to the desired location. Then try compiling a simple MPI hello world program, and running that. (Using `mpifort` and `mpirun`. You may need to set `MPICH_FC=/path/to/gfortram`)

If, in fact, you are able to do both of these tasks, then it might be worthwhile looking into ways to improve/upgrade the `install.sh` and other build logic to support this use case.

As for to what extent the `install.sh` script supports specifying an installation location for pre-requisite packages, I am not sure. Hopefully @rouson can weigh in on this.

The normal, more manual workflow to build in your local directory and then install to the system would be:

1. Take care of building and installing GCC, which looks something like:
   ```
   # double check your umask
   umask
   # for global installs you want something like 0022
   ./configure --prefix=/path/to/final/install/location <other options>
   make -j <some_polite_integer>
   make check # Run optional tests... probably don't do this with GCC
   sudo make install # copy everything with root to /path/to/final/install/location
   ```
2. Build MPICH using the GCC you just built. Ideally you don't have to mess around with special include dirs (e.g., `CPATH`) and `LD_LIBRARY_PATH` because it was installed to a standard location, or you setup GNU modules to handle it for you...
   ```
   ./configure --prefix=/path/to/final/install/location <other options>
   make -j <some_polite_integer>
   make check # If you're allowed to run MPI jobs outside a scheduler
   sudo make install
   ```
3. Build open coarrays directly with CMake using the GCC & MPICH that you just built and installed. The hardest part here will probably be making sure that open coarrays doesn't pick up another MPI implementation if you put the working MPICH and GCC in non standard locations and don't have something like GNU modules setup.
   ```
   export FC=/path/to/gfortran
   export CC=/path/to/gcc
   export MPICH_F90="$FC"
   export MPICH_CC="$CC"
   mkdir build
   cd build
   cmake -DCMAKE_INSTALL_PREFIX=/path/to/final/destination ..
   make -j <some_polite_integer>
   make check # if you can run MPI without a scheduler
   sudo make install
   ```

I'm going to close this issue for now, but I recommend asking Damian about whether the install.sh script can be told to install everything, or individual components, into a final location that needs root. Also, if you report back and have had success with the experiments I recommended above then we can re-open this.
