### ISSUE TITLE
Question: Why does saving content in allocatable array still lead to invalid memory reference?

### ISSUE THREAD

**Issue by evansste12432** [sourceryinstitute/OpenCoarrays#690]
I'm trying to use coarrays with a derived data type.  My derived data type has an allocatable component, and I'm careful to save the contents into a new allocatable space before deallocating my derived data type.  However, I get an error which describes an invalid memory reference, even though the contents were saved to a newly allocated location in memory.  I don't understand why this is happening.

Here's my program:

`program derive
    implicit none

    type :: matrix3
        integer, dimension(:,:,:), allocatable :: mtx3
    end type matrix3

    type(matrix3), dimension(:), codimension[:], allocatable :: tempnum
    integer, dimension(:,:), allocatable :: output
    integer :: n, noc, nor

    noc = 3
    nor = num_images()
    allocate(tempnum(nor) [*])
    do n = 1,nor
        allocate(tempnum(n)%mtx3(2,noc,2))
    end do

    tempnum(this_image())%mtx3 = reshape([(this_image(), n=1,4*noc)],[2,noc,2])
    syncall

    allocate(output(nor,noc))
    do n = 1,nor
        if (n == this_image()) then
            output(n,1:noc) = tempnum(n)%mtx3(2,1:noc,2)
        else
            output(n,1:noc) = tempnum(n)[n]%mtx3(2,1:noc,2)
        end if
        deallocate(tempnum(n)%mtx3)
    end do
    deallocate(tempnum)

end program derive`

My understanding is that the last loop of the program will save certain portions of the 'tempnum' coarray into a separate matrix, 'output'.  Because 'output' is never deallocated, shouldn't it have a stable, known place in memory?  So I don't understand why it's mentioning an invalid memory reference.

I've looked over this program quite a few times, and have run different renditions of it.  If someone is able to spot where I'm going wrong, I'd love to hear from you.

I apologize that the code portion of this message isn't completely in the code font.  I typed everything within the code ticks, but for some reason, the entire program isn't displaying in the code font.

Thanks for your time and attention.

**Comment by evansste12432** [comment]
I finally understand where I went wrong.  In the second loop, there's no need for me to deallocate each allocated component of 'tempnum'.  deallocating 'tempnum', after the loop, is all that's needed.  If I deallocate each component, within the loop, and then try to deallocate the entire 'tempnum' array, those components have already been deallocated, hence the error message.

**Comment by zbeekman** [comment]
@evansste12432 I'm glad you figured out what your issue was!

I'm still not convinced that this isn't a GFortran or OpenCoarrays bug, however. I don't recall whether or not deallocating an allocatable component of a derived type coarray object is an image control statement (implicit synchronization). Either way, deallocating the full coarray object should still be allowed, and should by an implicit synchronization point. It's possible that we're synchronizing *before* the deallocation, and then some images complete and the corresponding processes die while others are still trying to deallocate that memory? I'm not sure but this smells like a bug to me.

Could you try your original code again, but place a `sync all` before and immediately after the final `deallocate(tempnum)`? Does that make the error go away?

## Notes for opening issues in the future:

1. __USE THE ISSUE TEMPLATES__. They're there for a reason. In your post I could only just barely understand what the problem you were facing was since you never included the actual error message. Furthermore, if you're seeing a runtime error that looks suspicious please open a bug report. I'd rather have a false alarm bug report, than need to try to understand the issue you're facing when posed as a question.
2. Fenced code blocks need three back-tics to start and then three more to close, each on their own line. Alternatively, you can indent by 4 spaces. With the back-tics you can also specify the language for syntax highlighting, but GitHub usually guesses it correctly. e.g.,:
       
       ```Fortran
       program main
         implicit none
         integer, parameter n=100
         real u(n,n), v(n,n)
         integer i,j
       
         do concurrent( i = 1:n, j = 1:n)
           u(i,j) = cos(tau*i/real(n))
           v(i,j) = sin(tau*j/real(n))
         end do
       end program
       ```
   becomes
   ```Fortran
   program main
     implicit none
     integer, parameter n=100
     real u(n,n), v(n,n)
     integer i,j

     do concurrent( i = 1:n, j = 1:n)
       u(i,j) = cos(tau*i/real(n))
       v(i,j) = sin(tau*j/real(n))
     end do
   end program
   ```

**Comment by rouson** [comment]
@zbeekman I haven't read through all the details of this thread, but I can confirm that (de)allocating an allocatable component of a derived type coarray object does _not_ impose an implied synchronization.
