### ISSUE TITLE
Is there a -fcoarray=single,shared,distributed flag for OpenCoarrays like Intel ifort?

### ISSUE THREAD

**Issue by shahmoradi** [sourceryinstitute/OpenCoarrays#698]
The title has the question. If the answer is not, are there shared/distributed modes of compilation at all?

I get the following error when used,

```bash
gfortran: error: Unrecognized option: ‘shared’
gfortran: note: valid arguments to ‘-fcoarray=’ are: lib none single
```  
which means `caf` does not process the flag and passes it directly to `gfortran`.

Thanks for your impressive work and library!

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

The title of the issue should start with `Question:` followed by a
succinct title.

- [X] I am not reporting a bug or asking for a new feature
- [X] I am asking a general question about, e.g., the internal workings of this software, the direct use of this software, or use cases for this software, etc.
- [X] I have already searched for the answer to my question on [Google] and [Stack Overflow]

Please be descriptive, precise and concise. Thanks!

[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com

**Comment by rouson** [comment]
Thanks for your interest and feedback.

The `-fcoarray` options are described here: https://gcc.gnu.org/wiki/CoarrayLib.  Currently, the only two options are 

1. `-fcoarray=single` producing executable programs in which all calls to the parallel runtime library are stubs so only single-image execution works and 
2. `-fcoarray=lib` for linking to an actual parallel runtime library (OpenCoarrays).

Some gfortran developers started working on supporting `-fcoarray=native` for producing parallel executable programs able to run in without the need for an external library.   The currently envisioned library would work in shared-memory only.  See the GCC Bugzilla thread for updates: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88076.  If you're interested in such an option, I recommend adding yourself to the cc list on that Bugzilla issue so that you'll receive updates when changes happen or when someone posts a comment.  The gfortran developers sometimes use the cc list as a way to gage the amount of user interest in a Bugzilla issue.

I believe this answers your question so I'm closing this issue.  If you would like more information, feel free to reopen it.
