### ISSUE TITLE
Question: opencoarrays and openshmem via openmpi

### ISSUE THREAD

**Issue by jdeliacimec** [sourceryinstitute/OpenCoarrays#728]
- [x ] I am not reporting a bug or asking for a new feature
- [x ] I am asking a general question about, e.g., the internal workings of this software, the direct use of this software, or use cases for this software, etc.
- [x ] I have already searched for the answer to my question on [Google] and [Stack Overflow]

Dear developers. I regularly use opencoarrays successfully on laptops and PCs with x86_64, using Fedora 33, via git clone, make, gfortran, openmpi and so on, all ok (great!). But I would also like to experiment with the openshmem option available in openmpi: is that possible? And if the answer is yes, then how to do it or where to see it in the documentation? i.e. how to build libcaf_openshmem.a file? Thanks in advance. Regards. Jorge.

[Google]: https://www.google.com
[Stack Overflow]: https://stackoverflow.com

**Comment by rouson** [comment]
@jdeliacimec thanks for submitting this issue.  In the short term, the approach would be to modify [src/openshmem/Makefile] to build `libcaf_openshmem.a` and then link your program to it.  @afanfa wrote our OpenSHMEM layer and might have more advice but might not be available to respond to this. In the longer term, I would very much like to incorporate an option to build the OpenSHMEM layer using `install.sh` and to set it up to be invoked via the `caf` compiler wrapper.  I'm really glad to you submitted this issue because I'm more motivated to work on this when I know there's a user interested.  I'll see if I can find the time to look into this early next week if not sooner.

We found the OpenSHMEM layer invaluable on the [Coarray ICAR project] wherein we were working on a platform with immature support for MPI 3.1 one-sided communication so we weren't able to use our MPI layer beyond about 2,000 cores.  Having the ability to relink object files to `libcaf_openshmem.a` rather than `libcaf_mpi.a` without recompiling the application source code saved the day in terms of enabling us to run on more cores and even to get better performance than with MPI.

[src/openshmem/Makefile]: https://github.com/sourceryinstitute/OpenCoarrays/blob/main/src/openshmem/Makefile
[Coarray ICAR project]: https://github.com/sourceryinstitute/coarray-icar-paw17/blob/master/main.pdf

**Comment by jdeliacimec** [comment]
Dear Damian,

Thank you very much for your reply. 

I apologize for the delay in responding but I was "entertained" by an apparent 
small performance drop when I activated ucx in openmpi (already fixed). 

Below I continue to write interleaved: 

----- Mensaje original -----
> De: "Damian Rouson" 
> Para: "sourceryinstitute/OpenCoarrays" 
> CC: "jdelia" <jdelia@cimec.unl.edu.ar>, "Mention" 
> Enviado: Miércoles, 10 de Febrero 2021 17:31:30
> Asunto: Re: [sourceryinstitute/OpenCoarrays] Question: opencoarrays and openshmem via openmpi (#728)
>
> @jdeliacimec thanks for submitting this issue.  In the short term, the approach
> would be to modify [src/openshmem/Makefile] to build `libcaf_openshmem.a` and
> then link your program to it. 

Ok.

> @afanfa wrote our OpenSHMEM layer and might have more advice but might 
> not be available to respond to this. 

Bad luck...

> In the longer term, I would very much like to incorporate an option to build the OpenSHMEM 
> layer using `install.sh` and to set it up to be invoked via the `caf` compiler
> wrapper. 

It would be great! 

> I'm really glad to you submitted this issue because I'm more motivated to work on 
> this when I know there's a user interested.  

It would be nice if there were more interested users. 
Thanks to all of you for creating and maintaining Opencoarrays. 

> I'll see if I can find the time to look into this early next week if not sooner.

Ok. Thanks in advance.

> We found the OpenSHMEM layer invaluable on the [Coarray ICAR project] wherein we
> were working on a platform with immature support for MPI 3.1 one-sided
> communication so we weren't able to use our MPI layer beyond about 2,000 cores.

Well, I'm a long way from using 2000 cores ... 

> Having the ability to relink object files to `libcaf_openshmem.a` rather than
> `libcaf_mpi.a` without recompiling the application source code saved the day in
> terms of enabling us to run on more cores and even to get better performance
> than with MPI.

That would be very practical and interesting for an end user. 

Regards.
JorgeD.
